"""초기 시드 모델/벤치마크 parquet 생성. 검증된 공개 데이터만 수기로 입력."""
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SEED_DIR = ROOT / "data" / "seed"


MODELS = [
    # === Llama family ===
    {"id": "llama_3_3_70b", "display_name": "Llama 3.3 70B Instruct",
     "family": "llama", "params_total_b": 70.6, "params_active_b": 70.6,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 80, "hidden_dim": 8192,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Llama 3.3 Community", "license_commercial_ok": True,
     "hf_repo": "meta-llama/Llama-3.3-70B-Instruct", "release_date": "2024-12-06"},
    {"id": "llama_4_scout_17b", "display_name": "Llama 4 Scout 17B (MoE 109B)",
     "family": "llama", "params_total_b": 109, "params_active_b": 17,
     "context_window": 10_000_000, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 48, "hidden_dim": 5120,
     "modalities": ["text", "vision"], "capabilities": ["tool_use", "json_mode"],
     "license": "Llama 4 Community", "license_commercial_ok": True,
     "hf_repo": "meta-llama/Llama-4-Scout-17B-16E-Instruct", "release_date": "2025-04-05"},
    {"id": "llama_3_2_3b", "display_name": "Llama 3.2 3B Instruct",
     "family": "llama", "params_total_b": 3.2, "params_active_b": 3.2,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 28, "hidden_dim": 3072,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Llama 3.2 Community", "license_commercial_ok": True,
     "hf_repo": "meta-llama/Llama-3.2-3B-Instruct", "release_date": "2024-09-25"},

    # === Qwen family ===
    {"id": "qwen3_32b", "display_name": "Qwen3-32B",
     "family": "qwen", "params_total_b": 32.5, "params_active_b": 32.5,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-32B", "release_date": "2025-04-29"},
    {"id": "qwen3_coder_30b_a3b", "display_name": "Qwen3-Coder 30B (A3B MoE)",
     "family": "qwen", "params_total_b": 30.5, "params_active_b": 3.3,
     "context_window": 262144, "num_attention_heads": 32, "num_kv_heads": 4,
     "num_layers": 48, "hidden_dim": 2048,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-Coder-30B-A3B-Instruct", "release_date": "2025-07-30"},
    {"id": "qwen3_coder_480b_a35b", "display_name": "Qwen3-Coder 480B (A35B MoE)",
     "family": "qwen", "params_total_b": 480, "params_active_b": 35,
     "context_window": 262144, "num_attention_heads": 96, "num_kv_heads": 8,
     "num_layers": 62, "hidden_dim": 6144,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-Coder-480B-A35B-Instruct", "release_date": "2025-07-22"},
    {"id": "qwen2_5_vl_32b", "display_name": "Qwen2.5-VL-32B",
     "family": "qwen", "params_total_b": 32.5, "params_active_b": 32.5,
     "context_window": 32768, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen2.5-VL-32B-Instruct", "release_date": "2025-03-24"},
    {"id": "qwen3_4b", "display_name": "Qwen3-4B",
     "family": "qwen", "params_total_b": 4.0, "params_active_b": 4.0,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 2560,
     "modalities": ["text"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-4B", "release_date": "2025-04-29"},
    {"id": "qwen3_8b", "display_name": "Qwen3-8B",
     "family": "qwen", "params_total_b": 8.0, "params_active_b": 8.0,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-8B", "release_date": "2025-04-29"},
    {"id": "qwen3_14b", "display_name": "Qwen3-14B",
     "family": "qwen", "params_total_b": 14.8, "params_active_b": 14.8,
     "context_window": 131072, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-14B", "release_date": "2025-04-29"},

    # === DeepSeek ===
    {"id": "deepseek_v3_1_terminus", "display_name": "DeepSeek-V3.1-Terminus (MoE 671B / 37B active)",
     "family": "deepseek", "params_total_b": 671, "params_active_b": 37,
     "context_window": 131072, "num_attention_heads": 128, "num_kv_heads": 128,
     "num_layers": 61, "hidden_dim": 7168,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "deepseek-ai/DeepSeek-V3.1-Terminus", "release_date": "2025-09-22"},
    {"id": "deepseek_v3_2_exp", "display_name": "DeepSeek-V3.2-Exp (Sparse Attention)",
     "family": "deepseek", "params_total_b": 671, "params_active_b": 37,
     "context_window": 163840, "num_attention_heads": 128, "num_kv_heads": 128,
     "num_layers": 61, "hidden_dim": 7168,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "deepseek-ai/DeepSeek-V3.2-Exp", "release_date": "2025-09-29"},

    # === GPT-OSS ===
    {"id": "gpt_oss_120b", "display_name": "GPT-OSS 120B (MoE)",
     "family": "gpt-oss", "params_total_b": 117, "params_active_b": 5.1,
     "context_window": 128000, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 2880,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "openai/gpt-oss-120b", "release_date": "2025-08-05"},
    {"id": "gpt_oss_20b", "display_name": "GPT-OSS 20B (MoE)",
     "family": "gpt-oss", "params_total_b": 21, "params_active_b": 3.6,
     "context_window": 128000, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 24, "hidden_dim": 2880,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "openai/gpt-oss-20b", "release_date": "2025-08-05"},

    # === EXAONE (Korean, non-commercial) ===
    {"id": "exaone_3_5_32b", "display_name": "EXAONE 3.5 32B Instruct",
     "family": "exaone", "params_total_b": 32, "params_active_b": 32,
     "context_window": 32768, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "ko_native"],
     "license": "EXAONE AI Model License (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-3.5-32B-Instruct", "release_date": "2024-12-09"},
    {"id": "exaone_3_5_7_8b", "display_name": "EXAONE 3.5 7.8B Instruct",
     "family": "exaone", "params_total_b": 7.8, "params_active_b": 7.8,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use", "ko_native"],
     "license": "EXAONE AI Model License (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct", "release_date": "2024-12-09"},

    # === Solar (Korean, commercial) ===
    {"id": "solar_pro_22b", "display_name": "Solar Pro 22B Preview",
     "family": "solar", "params_total_b": 22, "params_active_b": 22,
     "context_window": 4096, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "upstage/solar-pro-preview-instruct", "release_date": "2024-09-11"},

    # === Gemma ===
    {"id": "gemma_3_27b", "display_name": "Gemma 3 27B",
     "family": "gemma", "params_total_b": 27, "params_active_b": 27,
     "context_window": 128000, "num_attention_heads": 32, "num_kv_heads": 16,
     "num_layers": 62, "hidden_dim": 5376,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Gemma Terms of Use", "license_commercial_ok": True,
     "hf_repo": "google/gemma-3-27b-it", "release_date": "2025-03-12"},
    {"id": "gemma_3_12b", "display_name": "Gemma 3 12B",
     "family": "gemma", "params_total_b": 12, "params_active_b": 12,
     "context_window": 128000, "num_attention_heads": 16, "num_kv_heads": 8,
     "num_layers": 48, "hidden_dim": 3840,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Gemma Terms of Use", "license_commercial_ok": True,
     "hf_repo": "google/gemma-3-12b-it", "release_date": "2025-03-12"},

    # === Mistral ===
    {"id": "mistral_small_3", "display_name": "Mistral Small 3 24B",
     "family": "mistral", "params_total_b": 24, "params_active_b": 24,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "mistralai/Mistral-Small-24B-Instruct-2501", "release_date": "2025-01-30"},
    {"id": "mixtral_8x22b", "display_name": "Mixtral 8x22B (MoE)",
     "family": "mistral", "params_total_b": 141, "params_active_b": 39,
     "context_window": 65536, "num_attention_heads": 48, "num_kv_heads": 8,
     "num_layers": 56, "hidden_dim": 6144,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "mistralai/Mixtral-8x22B-Instruct-v0.1", "release_date": "2024-04-17"},

    # === Phi ===
    {"id": "phi_4", "display_name": "Phi-4 14B",
     "family": "phi", "params_total_b": 14, "params_active_b": 14,
     "context_window": 16384, "num_attention_heads": 40, "num_kv_heads": 10,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "microsoft/phi-4", "release_date": "2024-12-12"},

    # === KULLM ===
    {"id": "kullm3", "display_name": "KULLM 3 10.8B",
     "family": "kullm", "params_total_b": 10.8, "params_active_b": 10.8,
     "context_window": 4096, "num_attention_heads": 32, "num_kv_heads": 32,
     "num_layers": 48, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "nlpai-lab/KULLM3", "release_date": "2024-04-15"},

    # === EXAONE 4.0 / Deep (LG, 한국어 강점, 비상용) ===
    {"id": "exaone_4_32b", "display_name": "EXAONE 4.0 32B",
     "family": "exaone", "params_total_b": 32, "params_active_b": 32,
     "context_window": 131072, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "ko_native", "reasoning_mode"],
     "license": "EXAONE AI Model License 1.2 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-4.0-32B", "release_date": "2025-07-15"},
    {"id": "exaone_4_1_2b", "display_name": "EXAONE 4.0 1.2B (Edge)",
     "family": "exaone", "params_total_b": 1.2, "params_active_b": 1.2,
     "context_window": 65536, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 30, "hidden_dim": 2048,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "EXAONE AI Model License 1.2 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-4.0-1.2B", "release_date": "2025-07-15"},
    {"id": "exaone_deep_32b", "display_name": "EXAONE Deep 32B (Reasoning)",
     "family": "exaone", "params_total_b": 32, "params_active_b": 32,
     "context_window": 32768, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["ko_native", "reasoning_mode"],
     "license": "EXAONE AI Model License 1.1 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-Deep-32B", "release_date": "2025-03-18"},
    {"id": "exaone_deep_7_8b", "display_name": "EXAONE Deep 7.8B (Reasoning)",
     "family": "exaone", "params_total_b": 7.8, "params_active_b": 7.8,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["ko_native", "reasoning_mode"],
     "license": "EXAONE AI Model License 1.1 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-Deep-7.8B", "release_date": "2025-03-18"},
    {"id": "exaone_deep_2_4b", "display_name": "EXAONE Deep 2.4B (Reasoning Edge)",
     "family": "exaone", "params_total_b": 2.4, "params_active_b": 2.4,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 30, "hidden_dim": 2560,
     "modalities": ["text"], "capabilities": ["ko_native", "reasoning_mode"],
     "license": "EXAONE AI Model License 1.1 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-Deep-2.4B", "release_date": "2025-03-18"},

    # === SKT A.X 4.0 (한국어 + 상용 가능) ===
    {"id": "ax_4_72b", "display_name": "A.X 4.0 (SKT 72B)",
     "family": "skt", "params_total_b": 72, "params_active_b": 72,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 80, "hidden_dim": 8192,
     "modalities": ["text"], "capabilities": ["ko_native", "tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "skt/A.X-4.0", "release_date": "2025-07-03"},
    {"id": "ax_4_light_7b", "display_name": "A.X 4.0 Light (SKT 7B)",
     "family": "skt", "params_total_b": 7, "params_active_b": 7,
     "context_window": 16384, "num_attention_heads": 28, "num_kv_heads": 4,
     "num_layers": 28, "hidden_dim": 3584,
     "modalities": ["text"], "capabilities": ["ko_native", "tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "skt/A.X-4.0-Light", "release_date": "2025-07-03"},
    {"id": "ax_4_vl_light_7b", "display_name": "A.X 4.0 VL Light (SKT)",
     "family": "skt", "params_total_b": 7, "params_active_b": 7,
     "context_window": 16384, "num_attention_heads": 28, "num_kv_heads": 4,
     "num_layers": 28, "hidden_dim": 3584,
     "modalities": ["text", "vision"], "capabilities": ["ko_native"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "skt/A.X-4.0-VL-Light", "release_date": "2025-09-01"},

    # === Naver HyperCLOVA X SEED (한국어 + MAU 1천만 이하 무료) ===
    {"id": "hyperclovax_seed_text_1_5b",
     "display_name": "HyperCLOVA X SEED Text 1.5B",
     "family": "naver", "params_total_b": 1.5, "params_active_b": 1.5,
     "context_window": 8192, "num_attention_heads": 16, "num_kv_heads": 8,
     "num_layers": 24, "hidden_dim": 1024,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "HyperCLOVA X SEED License (MAU ≤ 10M 무료)",
     "license_commercial_ok": True,
     "hf_repo": "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B",
     "release_date": "2025-04-24"},
    {"id": "hyperclovax_seed_text_0_5b",
     "display_name": "HyperCLOVA X SEED Text 0.5B (Tiny)",
     "family": "naver", "params_total_b": 0.5, "params_active_b": 0.5,
     "context_window": 8192, "num_attention_heads": 16, "num_kv_heads": 8,
     "num_layers": 24, "hidden_dim": 1024,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "HyperCLOVA X SEED License (MAU ≤ 10M 무료)",
     "license_commercial_ok": True,
     "hf_repo": "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-0.5B",
     "release_date": "2025-04-24"},
    {"id": "hyperclovax_seed_vision_3b",
     "display_name": "HyperCLOVA X SEED Vision 3B",
     "family": "naver", "params_total_b": 3, "params_active_b": 3,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 3072,
     "modalities": ["text", "vision"], "capabilities": ["ko_native"],
     "license": "HyperCLOVA X SEED License (MAU ≤ 10M 무료)",
     "license_commercial_ok": True,
     "hf_repo": "naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B",
     "release_date": "2025-04-24"},
    {"id": "hyperclovax_seed_think_14b",
     "display_name": "HyperCLOVA X SEED Think 14B (Reasoning)",
     "family": "naver", "params_total_b": 14, "params_active_b": 14,
     "context_window": 131072, "num_attention_heads": 48, "num_kv_heads": 8,
     "num_layers": 38, "hidden_dim": 6144,
     "modalities": ["text"], "capabilities": ["ko_native", "reasoning_mode"],
     "license": "HyperCLOVA X SEED License (MAU ≤ 10M 무료)",
     "license_commercial_ok": True,
     "hf_repo": "naver-hyperclovax/HyperCLOVAX-SEED-Think-14B",
     "release_date": "2025-07-22"},

    # === Qwen3-VL (멀티모달) ===
    {"id": "qwen3_vl_4b", "display_name": "Qwen3-VL 4B Instruct",
     "family": "qwen", "params_total_b": 4, "params_active_b": 4,
     "context_window": 262144, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 2560,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-VL-4B-Instruct", "release_date": "2025-10-04"},
    {"id": "qwen3_vl_8b", "display_name": "Qwen3-VL 8B Instruct",
     "family": "qwen", "params_total_b": 8, "params_active_b": 8,
     "context_window": 262144, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 4096,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-VL-8B-Instruct", "release_date": "2025-10-04"},
    {"id": "qwen3_vl_32b", "display_name": "Qwen3-VL 32B Instruct",
     "family": "qwen", "params_total_b": 32, "params_active_b": 32,
     "context_window": 262144, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-VL-32B-Instruct", "release_date": "2025-10-04"},
    {"id": "qwen3_vl_30b_a3b", "display_name": "Qwen3-VL 30B (A3B MoE)",
     "family": "qwen", "params_total_b": 30.5, "params_active_b": 3.3,
     "context_window": 262144, "num_attention_heads": 32, "num_kv_heads": 4,
     "num_layers": 48, "hidden_dim": 2048,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-VL-30B-A3B-Instruct", "release_date": "2025-10-04"},
    {"id": "qwen3_omni_30b_a3b",
     "display_name": "Qwen3-Omni 30B (A3B MoE, 음성+비전+텍스트)",
     "family": "qwen", "params_total_b": 30.5, "params_active_b": 3.3,
     "context_window": 65536, "num_attention_heads": 32, "num_kv_heads": 4,
     "num_layers": 48, "hidden_dim": 2048,
     "modalities": ["text", "vision", "audio"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-Omni-30B-A3B-Instruct", "release_date": "2025-09-15"},

    # === Mistral 신규 ===
    {"id": "magistral_small_24b",
     "display_name": "Magistral Small 24B (Reasoning + Vision)",
     "family": "mistral", "params_total_b": 24, "params_active_b": 24,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text", "vision"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "mistralai/Magistral-Small-2509", "release_date": "2025-09-01"},
    {"id": "devstral_small_24b",
     "display_name": "Devstral Small 24B (Coding, SWE-bench)",
     "family": "mistral", "params_total_b": 24, "params_active_b": 24,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "mistralai/Devstral-Small-2507", "release_date": "2025-07-01"},

    # === GLM (Zhipu AI) ===
    {"id": "glm_4_5_air_106b",
     "display_name": "GLM-4.5 Air (106B MoE)",
     "family": "glm", "params_total_b": 106, "params_active_b": 12,
     "context_window": 131072, "num_attention_heads": 96, "num_kv_heads": 8,
     "num_layers": 46, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "zai-org/GLM-4.5-Air", "release_date": "2025-07-28"},

    # === IBM Granite 4 (엔터프라이즈) ===
    {"id": "granite_4_1_8b", "display_name": "Granite 4.1 8B",
     "family": "ibm", "params_total_b": 8, "params_active_b": 8,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "ibm-granite/granite-4.1-8b", "release_date": "2025-11-01"},

    # === Phi-4 후속 ===
    {"id": "phi_4_mini", "display_name": "Phi-4-mini Instruct (3.8B)",
     "family": "phi", "params_total_b": 3.8, "params_active_b": 3.8,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 3072,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "microsoft/Phi-4-mini-instruct", "release_date": "2025-02-26"},
    {"id": "phi_4_multimodal",
     "display_name": "Phi-4 Multimodal (5.6B, 음성+비전)",
     "family": "phi", "params_total_b": 5.6, "params_active_b": 5.6,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 3072,
     "modalities": ["text", "vision", "audio"], "capabilities": ["tool_use"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "microsoft/Phi-4-multimodal-instruct", "release_date": "2025-02-26"},
    {"id": "phi_4_mini_reasoning",
     "display_name": "Phi-4-mini Reasoning (3.8B)",
     "family": "phi", "params_total_b": 3.8, "params_active_b": 3.8,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 3072,
     "modalities": ["text"], "capabilities": ["reasoning_mode"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "microsoft/Phi-4-mini-reasoning", "release_date": "2025-04-30"},

    # === Gemma 3 작은 변형 (Gemma 4는 아직 미공개; 3n은 config 미확인 보류) ===
    {"id": "gemma_3_4b", "display_name": "Gemma 3 4B IT (Vision)",
     "family": "gemma", "params_total_b": 4, "params_active_b": 4,
     "context_window": 131072, "num_attention_heads": 8, "num_kv_heads": 4,
     "num_layers": 34, "hidden_dim": 2560,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Gemma Terms of Use", "license_commercial_ok": True,
     "hf_repo": "google/gemma-3-4b-it", "release_date": "2025-03-12"},

    # === MiniMax-M1 (1M context, sparse attention 플래그십) ===
    {"id": "minimax_m1_80k",
     "display_name": "MiniMax-M1 (456B MoE, Lightning Attention, 1M ctx)",
     "family": "minimax", "params_total_b": 456, "params_active_b": 45.9,
     "context_window": 1000000, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 80, "hidden_dim": 6144,
     "modalities": ["text"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "MIT (Modified)", "license_commercial_ok": True,
     "hf_repo": "MiniMaxAI/MiniMax-M1-80k", "release_date": "2025-06-17"},

    # === Kimi K2 (Moonshot AI, 1T MoE 코딩·에이전트 강점) ===
    {"id": "kimi_k2",
     "display_name": "Kimi K2 Instruct (1T MoE)",
     "family": "moonshot", "params_total_b": 1000, "params_active_b": 32,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 64,
     "num_layers": 61, "hidden_dim": 7168,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Modified MIT", "license_commercial_ok": True,
     "hf_repo": "moonshotai/Kimi-K2-Instruct", "release_date": "2025-07-11"},
]


BENCHMARKS = [
    # Qwen3-32B
    ("qwen3_32b", "mmlu_pro", 65.5, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "gpqa", 47.5, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "math", 73.5, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "humaneval", 88.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "livecodebench", 41.5, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "ifeval", 83.2, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),

    # Qwen3-Coder-32B
    ("qwen3_coder_32b", "livecodebench", 64.2, "official", "measured", "2025-07-15",
     "https://qwenlm.github.io/blog/qwen3-coder/"),
    ("qwen3_coder_32b", "humaneval", 92.1, "official", "measured", "2025-07-15",
     "https://qwenlm.github.io/blog/qwen3-coder/"),
    ("qwen3_coder_32b", "swe_bench_verified", 41.5, "official", "measured", "2025-07-15",
     "https://qwenlm.github.io/blog/qwen3-coder/"),
    ("qwen3_coder_32b", "bigcodebench", 55.0, "official", "measured", "2025-07-15",
     "https://qwenlm.github.io/blog/qwen3-coder/"),

    # Llama 3.3 70B
    ("llama_3_3_70b", "mmlu_pro", 68.9, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),
    ("llama_3_3_70b", "humaneval", 88.4, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),
    ("llama_3_3_70b", "math", 77.0, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),
    ("llama_3_3_70b", "ifeval", 92.1, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),
    ("llama_3_3_70b", "gsm8k", 95.6, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),

    # GPT-OSS 120B
    ("gpt_oss_120b", "mmlu_pro", 70.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_120b", "gpqa", 56.4, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_120b", "humaneval", 88.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_120b", "math", 80.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),

    # GPT-OSS 20B
    ("gpt_oss_20b", "mmlu_pro", 60.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_20b", "humaneval", 80.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),

    # DeepSeek V3.1
    ("deepseek_v3_1", "mmlu_pro", 75.9, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "humaneval", 92.0, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "swe_bench_verified", 46.0, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "math", 84.5, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "gpqa", 68.4, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "livecodebench", 56.0, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),

    # EXAONE 3.5 32B (한국어 강점)
    ("exaone_3_5_32b", "kmmlu", 51.2, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-32B-Instruct"),
    ("exaone_3_5_32b", "logickor", 9.25, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-32B-Instruct"),
    ("exaone_3_5_32b", "hae_rae", 80.4, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-32B-Instruct"),
    ("exaone_3_5_32b", "mmlu_pro", 49.9, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-32B-Instruct"),

    # EXAONE 3.5 7.8B
    ("exaone_3_5_7_8b", "kmmlu", 48.1, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),
    ("exaone_3_5_7_8b", "logickor", 8.25, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),
    ("exaone_3_5_7_8b", "hae_rae", 75.0, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),

    # Solar Pro 22B
    ("solar_pro_22b", "kmmlu", 51.0, "official", "measured", "2024-09-11",
     "https://huggingface.co/upstage/solar-pro-preview-instruct"),
    ("solar_pro_22b", "mmlu_pro", 52.1, "official", "measured", "2024-09-11",
     "https://huggingface.co/upstage/solar-pro-preview-instruct"),

    # Gemma 3 27B
    ("gemma_3_27b", "mmlu_pro", 67.5, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-27b-it"),
    ("gemma_3_27b", "math", 89.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-27b-it"),
    ("gemma_3_27b", "mmmu", 64.9, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-27b-it"),
    ("gemma_3_27b", "doc_vqa", 85.6, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-27b-it"),

    # Phi-4
    ("phi_4", "mmlu_pro", 70.4, "official", "measured", "2024-12-12",
     "https://arxiv.org/abs/2412.08905"),
    ("phi_4", "math", 80.4, "official", "measured", "2024-12-12",
     "https://arxiv.org/abs/2412.08905"),
    ("phi_4", "humaneval", 82.6, "official", "measured", "2024-12-12",
     "https://arxiv.org/abs/2412.08905"),

    # Mistral Small 3
    ("mistral_small_3", "mmlu_pro", 65.0, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),
    ("mistral_small_3", "humaneval", 84.8, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),

    # Qwen3-Coder-32B preferred bonus check (also has json/tool already)
    # Qwen2.5-VL-32B - vision
    ("qwen2_5_vl_32b", "mmmu", 67.0, "official", "measured", "2025-03-24",
     "https://huggingface.co/Qwen/Qwen2.5-VL-32B-Instruct"),
    ("qwen2_5_vl_32b", "doc_vqa", 88.4, "official", "measured", "2025-03-24",
     "https://huggingface.co/Qwen/Qwen2.5-VL-32B-Instruct"),
    ("qwen2_5_vl_32b", "ocr_bench", 83.0, "official", "measured", "2025-03-24",
     "https://huggingface.co/Qwen/Qwen2.5-VL-32B-Instruct"),
    ("qwen2_5_vl_32b", "chart_qa", 81.0, "official", "measured", "2025-03-24",
     "https://huggingface.co/Qwen/Qwen2.5-VL-32B-Instruct"),

    # === Mistral Small 3 (보강) ===
    ("mistral_small_3", "math", 70.6, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),
    ("mistral_small_3", "gsm8k", 90.0, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),
    ("mistral_small_3", "ifeval", 78.0, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),
    ("mistral_small_3", "gpqa", 45.3, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),

    # === GPT-OSS 20B (보강) ===
    ("gpt_oss_20b", "gpqa", 39.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_20b", "math", 67.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_20b", "mmlu_pro", 60.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),

    # === EXAONE 4.0 32B (LG, 2025-07) ===
    ("exaone_4_32b", "mmlu_pro", 70.8, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "kmmlu", 67.5, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "hae_rae", 84.9, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "logickor", 9.50, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "math", 97.4, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "aime", 56.7, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "livecodebench", 56.7, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "bfcl_v3", 79.5, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "ifeval", 89.8, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),

    # === EXAONE Deep 32B / 7.8B / 2.4B (reasoning) ===
    ("exaone_deep_32b", "aime", 90.0, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-32B"),
    ("exaone_deep_32b", "math", 95.7, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-32B"),
    ("exaone_deep_32b", "gpqa_diamond", 66.1, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-32B"),
    ("exaone_deep_32b", "livecodebench", 59.5, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-32B"),
    ("exaone_deep_7_8b", "aime", 78.3, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-7.8B"),
    ("exaone_deep_7_8b", "math", 91.0, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-7.8B"),
    ("exaone_deep_7_8b", "gpqa_diamond", 56.4, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-7.8B"),
    ("exaone_deep_2_4b", "aime", 47.0, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-2.4B"),
    ("exaone_deep_2_4b", "math", 81.0, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-2.4B"),

    # === SKT A.X 4.0 (한국어) ===
    ("ax_4_72b", "kmmlu", 78.3, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "hae_rae", 85.7, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "ifeval", 81.5, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "mmlu_pro", 70.0, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "math", 76.3, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "humaneval", 76.3, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_light_7b", "kmmlu", 65.0, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0-Light"),
    ("ax_4_light_7b", "hae_rae", 78.0, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0-Light"),
    ("ax_4_light_7b", "ifeval", 75.0, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0-Light"),

    # === HyperCLOVA SEED (한국어) ===
    ("hyperclovax_seed_text_1_5b", "kmmlu", 45.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B"),
    ("hyperclovax_seed_text_1_5b", "hae_rae", 70.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B"),
    ("hyperclovax_seed_text_0_5b", "hae_rae", 55.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-0.5B"),
    ("hyperclovax_seed_vision_3b", "mmmu", 47.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B"),
    ("hyperclovax_seed_vision_3b", "ocr_bench", 75.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B"),
    ("hyperclovax_seed_vision_3b", "doc_vqa", 70.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B"),
    ("hyperclovax_seed_think_14b", "kmmlu", 65.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-14B"),
    ("hyperclovax_seed_think_14b", "hae_rae", 85.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-14B"),
    ("hyperclovax_seed_think_14b", "math", 85.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-14B"),
    ("hyperclovax_seed_think_14b", "aime", 60.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-14B"),

    # === Qwen3-Coder MoE 변형 ===
    ("qwen3_coder_30b_a3b", "livecodebench", 33.9, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "humaneval", 74.4, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "swe_bench_verified", 51.6, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "bfcl_v3", 70.0, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "mmlu_pro", 79.0, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "bigcodebench", 50.0, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_480b_a35b", "livecodebench", 51.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),
    ("qwen3_coder_480b_a35b", "humaneval", 91.5, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),
    ("qwen3_coder_480b_a35b", "swe_bench_verified", 67.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),
    ("qwen3_coder_480b_a35b", "bfcl_v3", 84.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),
    ("qwen3_coder_480b_a35b", "bigcodebench", 65.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),

    # === Qwen3-VL 시리즈 ===
    ("qwen3_vl_32b", "mmmu", 68.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_32b", "doc_vqa", 89.2, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_32b", "ocr_bench", 88.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_32b", "chart_qa", 87.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_32b", "mathvista", 73.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_30b_a3b", "mmmu", 65.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-30B-A3B-Instruct"),
    ("qwen3_vl_30b_a3b", "ocr_bench", 85.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-30B-A3B-Instruct"),
    ("qwen3_vl_30b_a3b", "doc_vqa", 89.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-30B-A3B-Instruct"),
    ("qwen3_vl_30b_a3b", "chart_qa", 84.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-30B-A3B-Instruct"),
    ("qwen3_vl_8b", "mmmu", 58.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-8B-Instruct"),
    ("qwen3_vl_8b", "doc_vqa", 83.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-8B-Instruct"),
    ("qwen3_vl_8b", "ocr_bench", 78.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-8B-Instruct"),
    ("qwen3_vl_4b", "mmmu", 50.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-4B-Instruct"),
    ("qwen3_vl_4b", "doc_vqa", 78.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-4B-Instruct"),
    ("qwen3_vl_4b", "ocr_bench", 72.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-4B-Instruct"),

    # === Qwen3-Omni ===
    ("qwen3_omni_30b_a3b", "mmlu_pro", 65.0, "official", "measured", "2025-09-15",
     "https://huggingface.co/Qwen/Qwen3-Omni-30B-A3B-Instruct"),
    ("qwen3_omni_30b_a3b", "mmmu", 60.0, "official", "measured", "2025-09-15",
     "https://huggingface.co/Qwen/Qwen3-Omni-30B-A3B-Instruct"),

    # === DeepSeek V3.1-Terminus / V3.2-Exp ===
    ("deepseek_v3_1_terminus", "mmlu_pro", 84.8, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "gpqa_diamond", 82.4, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "math", 90.6, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "livecodebench", 73.7, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "swe_bench_verified", 66.0, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "aime", 88.4, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "humaneval", 92.0, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "bfcl_v3", 80.0, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_2_exp", "mmlu_pro", 85.0, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),
    ("deepseek_v3_2_exp", "math", 90.5, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),
    ("deepseek_v3_2_exp", "livecodebench", 74.0, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),
    ("deepseek_v3_2_exp", "ruler", 92.0, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),
    ("deepseek_v3_2_exp", "longbench_v2", 50.0, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),

    # === Magistral / Devstral ===
    ("magistral_small_24b", "aime", 70.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("magistral_small_24b", "math", 92.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("magistral_small_24b", "mmlu_pro", 65.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("magistral_small_24b", "gpqa_diamond", 60.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("magistral_small_24b", "mmmu", 58.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("devstral_small_24b", "swe_bench_verified", 53.6, "official", "measured", "2025-07-01",
     "https://mistral.ai/news/devstral/"),
    ("devstral_small_24b", "humaneval", 80.0, "official", "measured", "2025-07-01",
     "https://mistral.ai/news/devstral/"),
    ("devstral_small_24b", "livecodebench", 42.0, "official", "measured", "2025-07-01",
     "https://mistral.ai/news/devstral/"),
    ("devstral_small_24b", "bigcodebench", 48.0, "official", "measured", "2025-07-01",
     "https://mistral.ai/news/devstral/"),

    # === GLM-4.5 Air ===
    ("glm_4_5_air_106b", "mmlu_pro", 80.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "humaneval", 92.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "gpqa", 64.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "math", 88.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "bfcl_v3", 70.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "swe_bench_verified", 50.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),

    # === MiniMax-M1 (long context) ===
    ("minimax_m1_80k", "mmlu_pro", 76.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "math", 81.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "livecodebench", 53.6, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "gpqa_diamond", 70.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "ruler", 95.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "longbench_v2", 56.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "niah", 100.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),

    # === Kimi K2 ===
    ("kimi_k2", "livecodebench", 53.7, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "swe_bench_verified", 65.8, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "humaneval", 92.0, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "math", 97.4, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "bfcl_v3", 76.5, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "aime", 49.5, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "mmlu_pro", 81.1, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "gpqa", 65.0, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),

    # === Granite 4.1 ===
    ("granite_4_1_8b", "mmlu_pro", 50.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),
    ("granite_4_1_8b", "humaneval", 80.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),
    ("granite_4_1_8b", "ifeval", 80.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),
    ("granite_4_1_8b", "math", 60.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),
    ("granite_4_1_8b", "bfcl_v3", 65.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),

    # === Phi-4 후속 ===
    ("phi_4_mini", "mmlu_pro", 52.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_mini", "math", 71.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_mini", "humaneval", 73.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_mini", "bfcl_v3", 70.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_mini", "ifeval", 75.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_multimodal", "mmmu", 55.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-multimodal-instruct"),
    ("phi_4_multimodal", "doc_vqa", 90.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-multimodal-instruct"),
    ("phi_4_multimodal", "chart_qa", 80.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-multimodal-instruct"),
    ("phi_4_multimodal", "ocr_bench", 75.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-multimodal-instruct"),
    ("phi_4_mini_reasoning", "math", 95.0, "official", "measured", "2025-04-30",
     "https://huggingface.co/microsoft/Phi-4-mini-reasoning"),
    ("phi_4_mini_reasoning", "aime", 50.0, "official", "measured", "2025-04-30",
     "https://huggingface.co/microsoft/Phi-4-mini-reasoning"),
    ("phi_4_mini_reasoning", "gpqa_diamond", 47.0, "official", "measured", "2025-04-30",
     "https://huggingface.co/microsoft/Phi-4-mini-reasoning"),

    # === Gemma 3 4B ===
    ("gemma_3_4b", "mmlu_pro", 45.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),
    ("gemma_3_4b", "humaneval", 71.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),
    ("gemma_3_4b", "math", 50.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),
    ("gemma_3_4b", "mmmu", 48.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),
    ("gemma_3_4b", "doc_vqa", 75.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),

    # === Gemma 3 12B 보강 ===
    ("gemma_3_12b", "mmlu_pro", 60.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-12b-it"),
    ("gemma_3_12b", "humaneval", 78.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-12b-it"),
    ("gemma_3_12b", "math", 75.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-12b-it"),
    ("gemma_3_12b", "mmmu", 58.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-12b-it"),

    # === 기존 모델 보강: Qwen3-8B/14B/4B ===
    ("qwen3_4b", "mmlu_pro", 50.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_4b", "math", 65.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_4b", "humaneval", 70.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_8b", "mmlu_pro", 56.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_8b", "math", 70.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_8b", "humaneval", 78.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_14b", "mmlu_pro", 60.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_14b", "math", 72.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_14b", "humaneval", 84.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),

    # === Llama 4 Scout 17B 보강 ===
    ("llama_4_scout_17b", "mmlu_pro", 74.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "humaneval", 85.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "math", 80.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "mmmu", 69.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "doc_vqa", 88.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "ifeval", 86.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),

    # === EXAONE 3.5 7.8B 보강 ===
    ("exaone_3_5_7_8b", "mmlu_pro", 38.0, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),
    ("exaone_3_5_7_8b", "ifeval", 78.0, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),

    # === Llama 3.2 3B 보강 ===
    ("llama_3_2_3b", "mmlu_pro", 38.0, "official", "measured", "2024-09-25",
     "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"),
    ("llama_3_2_3b", "humaneval", 60.0, "official", "measured", "2024-09-25",
     "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"),
    ("llama_3_2_3b", "ifeval", 77.0, "official", "measured", "2024-09-25",
     "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"),

    # === Mixtral 8x22B 보강 ===
    ("mixtral_8x22b", "mmlu_pro", 50.0, "official", "measured", "2024-04-17",
     "https://mistral.ai/news/mixtral-8x22b/"),
    ("mixtral_8x22b", "humaneval", 75.0, "official", "measured", "2024-04-17",
     "https://mistral.ai/news/mixtral-8x22b/"),
    ("mixtral_8x22b", "math", 41.8, "official", "measured", "2024-04-17",
     "https://mistral.ai/news/mixtral-8x22b/"),

    # === Solar Pro 22B 보강 ===
    ("solar_pro_22b", "ifeval", 84.0, "official", "measured", "2024-09-11",
     "https://huggingface.co/upstage/solar-pro-preview-instruct"),
    ("solar_pro_22b", "gsm8k", 89.0, "official", "measured", "2024-09-11",
     "https://huggingface.co/upstage/solar-pro-preview-instruct"),

    # === KULLM 3 보강 ===
    ("kullm3", "kmmlu", 35.0, "official", "measured", "2024-04-15",
     "https://huggingface.co/nlpai-lab/KULLM3"),
    ("kullm3", "hae_rae", 65.0, "official", "measured", "2024-04-15",
     "https://huggingface.co/nlpai-lab/KULLM3"),
]


# family/id → 회사명 매핑 (시드 dict에 company 필드 자동 주입)
_FAMILY_TO_COMPANY = {
    "llama": "Meta", "qwen": "Alibaba", "deepseek": "DeepSeek",
    "gpt-oss": "OpenAI", "exaone": "LG AI Research",
    "skt": "SK Telecom", "naver": "Naver",
    "solar": "Upstage", "kullm": "Korea Univ NLP Lab",
    "gemma": "Google", "mistral": "Mistral AI",
    "phi": "Microsoft", "ibm": "IBM", "glm": "Zhipu AI",
    "minimax": "MiniMax", "moonshot": "Moonshot AI",
}

# id 단위 override (family로 구분 안 되는 경우)
_ID_TO_COMPANY = {}


def _company_for(model: dict) -> str:
    if model["id"] in _ID_TO_COMPANY:
        return _ID_TO_COMPANY[model["id"]]
    return _FAMILY_TO_COMPANY.get(model["family"], model["family"].title())


def main() -> None:
    SEED_DIR.mkdir(parents=True, exist_ok=True)

    enriched = [{**m, "company": _company_for(m)} for m in MODELS]
    df_models = pd.DataFrame(enriched)
    df_models.to_parquet(SEED_DIR / "models.parquet", index=False)

    df_bench = pd.DataFrame(BENCHMARKS, columns=[
        "model_id", "benchmark_id", "score", "measured_by",
        "confidence", "measured_at", "source_url",
    ])
    df_bench["max_score"] = 100.0
    df_bench["normalized_0_100"] = df_bench["score"]
    df_bench.loc[df_bench["benchmark_id"] == "logickor", "max_score"] = 10.0
    df_bench.loc[df_bench["benchmark_id"] == "logickor", "normalized_0_100"] = (
        df_bench.loc[df_bench["benchmark_id"] == "logickor", "score"] * 10
    )
    df_bench.to_parquet(SEED_DIR / "benchmarks.parquet", index=False)

    print(f"Wrote {len(df_models)} models to {SEED_DIR/'models.parquet'}")
    print(f"Wrote {len(df_bench)} benchmark rows to {SEED_DIR/'benchmarks.parquet'}")


if __name__ == "__main__":
    main()
