"""초기 시드 모델/벤치마크 parquet 생성. 검증된 공개 데이터만 수기로 입력."""
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SEED_DIR = ROOT / "data" / "seed"


MODELS = [
    # === Llama family ===
    {"id": "llama_3_3_70b", "display_name": "Llama 3.3 70B Instruct",
     "family": "llama", "params_total_b": 70.6, "params_active_b": 70.6,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 80, "hidden_dim": 8192,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Llama 3.3 Community", "license_commercial_ok": True,
     "hf_repo": "meta-llama/Llama-3.3-70B-Instruct", "release_date": "2024-12-06"},
    {"id": "llama_4_scout_17b", "display_name": "Llama 4 Scout 17B (MoE 109B)",
     "family": "llama", "params_total_b": 109, "params_active_b": 17,
     "context_window": 10_000_000, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 48, "hidden_dim": 5120,
     "modalities": ["text", "vision"], "capabilities": ["tool_use", "json_mode"],
     "license": "Llama 4 Community", "license_commercial_ok": True,
     "hf_repo": "meta-llama/Llama-4-Scout-17B-16E-Instruct", "release_date": "2025-04-05"},
    {"id": "llama_3_2_3b", "display_name": "Llama 3.2 3B Instruct",
     "family": "llama", "params_total_b": 3.2, "params_active_b": 3.2,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 28, "hidden_dim": 3072,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Llama 3.2 Community", "license_commercial_ok": True,
     "hf_repo": "meta-llama/Llama-3.2-3B-Instruct", "release_date": "2024-09-25"},

    # === Qwen family ===
    {"id": "qwen3_32b", "display_name": "Qwen3-32B",
     "family": "qwen", "params_total_b": 32.5, "params_active_b": 32.5,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-32B", "release_date": "2025-04-29"},
    {"id": "qwen3_coder_30b_a3b", "display_name": "Qwen3-Coder 30B (A3B MoE)",
     "family": "qwen", "params_total_b": 30.5, "params_active_b": 3.3,
     "context_window": 262144, "num_attention_heads": 32, "num_kv_heads": 4,
     "num_layers": 48, "hidden_dim": 2048,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-Coder-30B-A3B-Instruct", "release_date": "2025-07-30"},
    {"id": "qwen3_coder_480b_a35b", "display_name": "Qwen3-Coder 480B (A35B MoE)",
     "family": "qwen", "params_total_b": 480, "params_active_b": 35,
     "context_window": 262144, "num_attention_heads": 96, "num_kv_heads": 8,
     "num_layers": 62, "hidden_dim": 6144,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-Coder-480B-A35B-Instruct", "release_date": "2025-07-22"},
    {"id": "qwen2_5_vl_32b", "display_name": "Qwen2.5-VL-32B",
     "family": "qwen", "params_total_b": 32.5, "params_active_b": 32.5,
     "context_window": 32768, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen2.5-VL-32B-Instruct", "release_date": "2025-03-24"},
    {"id": "qwen3_4b", "display_name": "Qwen3-4B",
     "family": "qwen", "params_total_b": 4.0, "params_active_b": 4.0,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 2560,
     "modalities": ["text"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-4B", "release_date": "2025-04-29"},
    {"id": "qwen3_8b", "display_name": "Qwen3-8B",
     "family": "qwen", "params_total_b": 8.0, "params_active_b": 8.0,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-8B", "release_date": "2025-04-29"},
    {"id": "qwen3_14b", "display_name": "Qwen3-14B",
     "family": "qwen", "params_total_b": 14.8, "params_active_b": 14.8,
     "context_window": 131072, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-14B", "release_date": "2025-04-29"},

    # === DeepSeek ===
    {"id": "deepseek_v3_1_terminus", "display_name": "DeepSeek-V3.1-Terminus (MoE 671B / 37B active)",
     "family": "deepseek", "params_total_b": 671, "params_active_b": 37,
     "context_window": 131072, "num_attention_heads": 128, "num_kv_heads": 128,
     "num_layers": 61, "hidden_dim": 7168,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "deepseek-ai/DeepSeek-V3.1-Terminus", "release_date": "2025-09-22"},
    {"id": "deepseek_v3_2_exp", "display_name": "DeepSeek-V3.2-Exp (Sparse Attention)",
     "family": "deepseek", "params_total_b": 671, "params_active_b": 37,
     "context_window": 163840, "num_attention_heads": 128, "num_kv_heads": 128,
     "num_layers": 61, "hidden_dim": 7168,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "deepseek-ai/DeepSeek-V3.2-Exp", "release_date": "2025-09-29"},

    # === GPT-OSS ===
    {"id": "gpt_oss_120b", "display_name": "GPT-OSS 120B (MoE)",
     "family": "gpt-oss", "params_total_b": 117, "params_active_b": 5.1,
     "context_window": 128000, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 2880,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "openai/gpt-oss-120b", "release_date": "2025-08-05"},
    {"id": "gpt_oss_20b", "display_name": "GPT-OSS 20B (MoE)",
     "family": "gpt-oss", "params_total_b": 21, "params_active_b": 3.6,
     "context_window": 128000, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 24, "hidden_dim": 2880,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "openai/gpt-oss-20b", "release_date": "2025-08-05"},

    # === EXAONE (Korean, non-commercial) ===
    {"id": "exaone_3_5_32b", "display_name": "EXAONE 3.5 32B Instruct",
     "family": "exaone", "params_total_b": 32, "params_active_b": 32,
     "context_window": 32768, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "ko_native"],
     "license": "EXAONE AI Model License (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-3.5-32B-Instruct", "release_date": "2024-12-09"},
    {"id": "exaone_3_5_7_8b", "display_name": "EXAONE 3.5 7.8B Instruct",
     "family": "exaone", "params_total_b": 7.8, "params_active_b": 7.8,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use", "ko_native"],
     "license": "EXAONE AI Model License (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct", "release_date": "2024-12-09"},

    # === Solar (Korean, commercial) ===
    {"id": "solar_pro_22b", "display_name": "Solar Pro 22B Preview",
     "family": "solar", "params_total_b": 22, "params_active_b": 22,
     "context_window": 4096, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "upstage/solar-pro-preview-instruct", "release_date": "2024-09-11"},

    # === Gemma ===
    {"id": "gemma_3_27b", "display_name": "Gemma 3 27B",
     "family": "gemma", "params_total_b": 27, "params_active_b": 27,
     "context_window": 128000, "num_attention_heads": 32, "num_kv_heads": 16,
     "num_layers": 62, "hidden_dim": 5376,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Gemma Terms of Use", "license_commercial_ok": True,
     "hf_repo": "google/gemma-3-27b-it", "release_date": "2025-03-12"},
    {"id": "gemma_3_12b", "display_name": "Gemma 3 12B",
     "family": "gemma", "params_total_b": 12, "params_active_b": 12,
     "context_window": 128000, "num_attention_heads": 16, "num_kv_heads": 8,
     "num_layers": 48, "hidden_dim": 3840,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Gemma Terms of Use", "license_commercial_ok": True,
     "hf_repo": "google/gemma-3-12b-it", "release_date": "2025-03-12"},

    # === Mistral ===
    {"id": "mistral_small_3", "display_name": "Mistral Small 3 24B",
     "family": "mistral", "params_total_b": 24, "params_active_b": 24,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "mistralai/Mistral-Small-24B-Instruct-2501", "release_date": "2025-01-30"},
    {"id": "mixtral_8x22b", "display_name": "Mixtral 8x22B (MoE)",
     "family": "mistral", "params_total_b": 141, "params_active_b": 39,
     "context_window": 65536, "num_attention_heads": 48, "num_kv_heads": 8,
     "num_layers": 56, "hidden_dim": 6144,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "mistralai/Mixtral-8x22B-Instruct-v0.1", "release_date": "2024-04-17"},

    # === Phi ===
    {"id": "phi_4", "display_name": "Phi-4 14B",
     "family": "phi", "params_total_b": 14, "params_active_b": 14,
     "context_window": 16384, "num_attention_heads": 40, "num_kv_heads": 10,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "microsoft/phi-4", "release_date": "2024-12-12"},

    # === KULLM ===
    {"id": "kullm3", "display_name": "KULLM 3 10.8B",
     "family": "kullm", "params_total_b": 10.8, "params_active_b": 10.8,
     "context_window": 4096, "num_attention_heads": 32, "num_kv_heads": 32,
     "num_layers": 48, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "nlpai-lab/KULLM3", "release_date": "2024-04-15"},

    # === EXAONE 4.0 / Deep (LG, 한국어 강점, 비상용) ===
    {"id": "exaone_4_32b", "display_name": "EXAONE 4.0 32B",
     "family": "exaone", "params_total_b": 32, "params_active_b": 32,
     "context_window": 131072, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "ko_native", "reasoning_mode"],
     "license": "EXAONE AI Model License 1.2 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-4.0-32B", "release_date": "2025-07-15"},
    {"id": "exaone_4_1_2b", "display_name": "EXAONE 4.0 1.2B (Edge)",
     "family": "exaone", "params_total_b": 1.2, "params_active_b": 1.2,
     "context_window": 65536, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 30, "hidden_dim": 2048,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "EXAONE AI Model License 1.2 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-4.0-1.2B", "release_date": "2025-07-15"},
    {"id": "exaone_deep_32b", "display_name": "EXAONE Deep 32B (Reasoning)",
     "family": "exaone", "params_total_b": 32, "params_active_b": 32,
     "context_window": 32768, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["ko_native", "reasoning_mode"],
     "license": "EXAONE AI Model License 1.1 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-Deep-32B", "release_date": "2025-03-18"},
    {"id": "exaone_deep_7_8b", "display_name": "EXAONE Deep 7.8B (Reasoning)",
     "family": "exaone", "params_total_b": 7.8, "params_active_b": 7.8,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["ko_native", "reasoning_mode"],
     "license": "EXAONE AI Model License 1.1 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-Deep-7.8B", "release_date": "2025-03-18"},
    {"id": "exaone_deep_2_4b", "display_name": "EXAONE Deep 2.4B (Reasoning Edge)",
     "family": "exaone", "params_total_b": 2.4, "params_active_b": 2.4,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 30, "hidden_dim": 2560,
     "modalities": ["text"], "capabilities": ["ko_native", "reasoning_mode"],
     "license": "EXAONE AI Model License 1.1 (non-commercial)",
     "license_commercial_ok": False,
     "hf_repo": "LGAI-EXAONE/EXAONE-Deep-2.4B", "release_date": "2025-03-18"},

    # === SKT A.X 4.0 (한국어 + 상용 가능) ===
    {"id": "ax_4_72b", "display_name": "A.X 4.0 (SKT 72B)",
     "family": "skt", "params_total_b": 72, "params_active_b": 72,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 80, "hidden_dim": 8192,
     "modalities": ["text"], "capabilities": ["ko_native", "tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "skt/A.X-4.0", "release_date": "2025-07-03"},
    {"id": "ax_4_light_7b", "display_name": "A.X 4.0 Light (SKT 7B)",
     "family": "skt", "params_total_b": 7, "params_active_b": 7,
     "context_window": 16384, "num_attention_heads": 28, "num_kv_heads": 4,
     "num_layers": 28, "hidden_dim": 3584,
     "modalities": ["text"], "capabilities": ["ko_native", "tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "skt/A.X-4.0-Light", "release_date": "2025-07-03"},
    {"id": "ax_4_vl_light_7b", "display_name": "A.X 4.0 VL Light (SKT)",
     "family": "skt", "params_total_b": 7, "params_active_b": 7,
     "context_window": 16384, "num_attention_heads": 28, "num_kv_heads": 4,
     "num_layers": 28, "hidden_dim": 3584,
     "modalities": ["text", "vision"], "capabilities": ["ko_native"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "skt/A.X-4.0-VL-Light", "release_date": "2025-09-01"},

    # === Naver HyperCLOVA X SEED (한국어 + MAU 1천만 이하 무료) ===
    {"id": "hyperclovax_seed_text_1_5b",
     "display_name": "HyperCLOVA X SEED Text 1.5B",
     "family": "naver", "params_total_b": 1.5, "params_active_b": 1.5,
     "context_window": 8192, "num_attention_heads": 16, "num_kv_heads": 8,
     "num_layers": 24, "hidden_dim": 1024,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "HyperCLOVA X SEED License (MAU ≤ 10M 무료)",
     "license_commercial_ok": True,
     "hf_repo": "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B",
     "release_date": "2025-04-24"},
    {"id": "hyperclovax_seed_text_0_5b",
     "display_name": "HyperCLOVA X SEED Text 0.5B (Tiny)",
     "family": "naver", "params_total_b": 0.5, "params_active_b": 0.5,
     "context_window": 8192, "num_attention_heads": 16, "num_kv_heads": 8,
     "num_layers": 24, "hidden_dim": 1024,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "HyperCLOVA X SEED License (MAU ≤ 10M 무료)",
     "license_commercial_ok": True,
     "hf_repo": "naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-0.5B",
     "release_date": "2025-04-24"},
    {"id": "hyperclovax_seed_vision_3b",
     "display_name": "HyperCLOVA X SEED Vision 3B",
     "family": "naver", "params_total_b": 3, "params_active_b": 3,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 3072,
     "modalities": ["text", "vision"], "capabilities": ["ko_native"],
     "license": "HyperCLOVA X SEED License (MAU ≤ 10M 무료)",
     "license_commercial_ok": True,
     "hf_repo": "naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B",
     "release_date": "2025-04-24"},
    {"id": "hyperclovax_seed_think_14b",
     "display_name": "HyperCLOVA X SEED Think 14B (Reasoning)",
     "family": "naver", "params_total_b": 14, "params_active_b": 14,
     "context_window": 131072, "num_attention_heads": 48, "num_kv_heads": 8,
     "num_layers": 38, "hidden_dim": 6144,
     "modalities": ["text"], "capabilities": ["ko_native", "reasoning_mode"],
     "license": "HyperCLOVA X SEED License (MAU ≤ 10M 무료)",
     "license_commercial_ok": True,
     "hf_repo": "naver-hyperclovax/HyperCLOVAX-SEED-Think-14B",
     "release_date": "2025-07-22"},

    # === Qwen3-VL (멀티모달) ===
    {"id": "qwen3_vl_4b", "display_name": "Qwen3-VL 4B Instruct",
     "family": "qwen", "params_total_b": 4, "params_active_b": 4,
     "context_window": 262144, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 2560,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-VL-4B-Instruct", "release_date": "2025-10-04"},
    {"id": "qwen3_vl_8b", "display_name": "Qwen3-VL 8B Instruct",
     "family": "qwen", "params_total_b": 8, "params_active_b": 8,
     "context_window": 262144, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 4096,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-VL-8B-Instruct", "release_date": "2025-10-04"},
    {"id": "qwen3_vl_32b", "display_name": "Qwen3-VL 32B Instruct",
     "family": "qwen", "params_total_b": 32, "params_active_b": 32,
     "context_window": 262144, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-VL-32B-Instruct", "release_date": "2025-10-04"},
    {"id": "qwen3_vl_30b_a3b", "display_name": "Qwen3-VL 30B (A3B MoE)",
     "family": "qwen", "params_total_b": 30.5, "params_active_b": 3.3,
     "context_window": 262144, "num_attention_heads": 32, "num_kv_heads": 4,
     "num_layers": 48, "hidden_dim": 2048,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-VL-30B-A3B-Instruct", "release_date": "2025-10-04"},
    {"id": "qwen3_omni_30b_a3b",
     "display_name": "Qwen3-Omni 30B (A3B MoE, 음성+비전+텍스트)",
     "family": "qwen", "params_total_b": 30.5, "params_active_b": 3.3,
     "context_window": 65536, "num_attention_heads": 32, "num_kv_heads": 4,
     "num_layers": 48, "hidden_dim": 2048,
     "modalities": ["text", "vision", "audio"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/Qwen3-Omni-30B-A3B-Instruct", "release_date": "2025-09-15"},

    # === Mistral 신규 ===
    {"id": "magistral_small_24b",
     "display_name": "Magistral Small 24B (Reasoning + Vision)",
     "family": "mistral", "params_total_b": 24, "params_active_b": 24,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text", "vision"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "mistralai/Magistral-Small-2509", "release_date": "2025-09-01"},
    {"id": "devstral_small_24b",
     "display_name": "Devstral Small 24B (Coding, SWE-bench)",
     "family": "mistral", "params_total_b": 24, "params_active_b": 24,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "mistralai/Devstral-Small-2507", "release_date": "2025-07-01"},

    # === GLM (Zhipu AI) ===
    {"id": "glm_4_5_air_106b",
     "display_name": "GLM-4.5 Air (106B MoE)",
     "family": "glm", "params_total_b": 106, "params_active_b": 12,
     "context_window": 131072, "num_attention_heads": 96, "num_kv_heads": 8,
     "num_layers": 46, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "zai-org/GLM-4.5-Air", "release_date": "2025-07-28"},

    # === IBM Granite 4 (엔터프라이즈) ===
    {"id": "granite_4_1_8b", "display_name": "Granite 4.1 8B",
     "family": "ibm", "params_total_b": 8, "params_active_b": 8,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "ibm-granite/granite-4.1-8b", "release_date": "2025-11-01"},

    # === Phi-4 후속 ===
    {"id": "phi_4_mini", "display_name": "Phi-4-mini Instruct (3.8B)",
     "family": "phi", "params_total_b": 3.8, "params_active_b": 3.8,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 3072,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "microsoft/Phi-4-mini-instruct", "release_date": "2025-02-26"},
    {"id": "phi_4_multimodal",
     "display_name": "Phi-4 Multimodal (5.6B, 음성+비전)",
     "family": "phi", "params_total_b": 5.6, "params_active_b": 5.6,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 3072,
     "modalities": ["text", "vision", "audio"], "capabilities": ["tool_use"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "microsoft/Phi-4-multimodal-instruct", "release_date": "2025-02-26"},
    {"id": "phi_4_mini_reasoning",
     "display_name": "Phi-4-mini Reasoning (3.8B)",
     "family": "phi", "params_total_b": 3.8, "params_active_b": 3.8,
     "context_window": 131072, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 3072,
     "modalities": ["text"], "capabilities": ["reasoning_mode"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "microsoft/Phi-4-mini-reasoning", "release_date": "2025-04-30"},

    # === Gemma 3 작은 변형 (Gemma 4는 아직 미공개; 3n은 config 미확인 보류) ===
    {"id": "gemma_3_4b", "display_name": "Gemma 3 4B IT (Vision)",
     "family": "gemma", "params_total_b": 4, "params_active_b": 4,
     "context_window": 131072, "num_attention_heads": 8, "num_kv_heads": 4,
     "num_layers": 34, "hidden_dim": 2560,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Gemma Terms of Use", "license_commercial_ok": True,
     "hf_repo": "google/gemma-3-4b-it", "release_date": "2025-03-12"},

    # === MiniMax-M1 (1M context, sparse attention 플래그십) ===
    {"id": "minimax_m1_80k",
     "display_name": "MiniMax-M1 (456B MoE, Lightning Attention, 1M ctx)",
     "family": "minimax", "params_total_b": 456, "params_active_b": 45.9,
     "context_window": 1000000, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 80, "hidden_dim": 6144,
     "modalities": ["text"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "MIT (Modified)", "license_commercial_ok": True,
     "hf_repo": "MiniMaxAI/MiniMax-M1-80k", "release_date": "2025-06-17"},

    # === Kimi K2 (Moonshot AI, 1T MoE 코딩·에이전트 강점) ===
    {"id": "kimi_k2",
     "display_name": "Kimi K2 Instruct (1T MoE)",
     "family": "moonshot", "params_total_b": 1000, "params_active_b": 32,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 64,
     "num_layers": 61, "hidden_dim": 7168,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "Modified MIT", "license_commercial_ok": True,
     "hf_repo": "moonshotai/Kimi-K2-Instruct", "release_date": "2025-07-11"},

    # ===== 2026-05 추가 트렌드 =====
    # === Tencent Hunyuan ===
    {"id": "hunyuan_large", "display_name": "Hunyuan-Large 389B (A52B)",
     "family": "hunyuan", "params_total_b": 389, "params_active_b": 52,
     "context_window": 256000, "num_attention_heads": 80, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 6400,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Tencent Hunyuan Community", "license_commercial_ok": True,
     "hf_repo": "tencent/Tencent-Hunyuan-Large", "release_date": "2024-11-05"},
    {"id": "hunyuan_a13b", "display_name": "Hunyuan-A13B (80B MoE)",
     "family": "hunyuan", "params_total_b": 80, "params_active_b": 13,
     "context_window": 256000, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Tencent Hunyuan Community", "license_commercial_ok": True,
     "hf_repo": "tencent/Hunyuan-A13B-Instruct", "release_date": "2025-06-27"},

    # === 01.AI Yi ===
    {"id": "yi_1_5_34b", "display_name": "Yi-1.5 34B Chat",
     "family": "yi", "params_total_b": 34, "params_active_b": 34,
     "context_window": 4096, "num_attention_heads": 56, "num_kv_heads": 8,
     "num_layers": 60, "hidden_dim": 7168,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "01-ai/Yi-1.5-34B-Chat", "release_date": "2024-05-13"},
    {"id": "yi_1_5_9b", "display_name": "Yi-1.5 9B Chat",
     "family": "yi", "params_total_b": 9, "params_active_b": 9,
     "context_window": 4096, "num_attention_heads": 32, "num_kv_heads": 4,
     "num_layers": 48, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "01-ai/Yi-1.5-9B-Chat", "release_date": "2024-05-13"},
    {"id": "yi_coder_9b", "display_name": "Yi-Coder 9B Chat",
     "family": "yi", "params_total_b": 9, "params_active_b": 9,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 4,
     "num_layers": 48, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "01-ai/Yi-Coder-9B-Chat", "release_date": "2024-09-04"},

    # === Shanghai AI Lab InternLM/InternVL ===
    {"id": "internlm3_8b", "display_name": "InternLM3 8B Instruct",
     "family": "internlm", "params_total_b": 8, "params_active_b": 8,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 2,
     "num_layers": 48, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use", "reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "internlm/internlm3-8b-instruct", "release_date": "2025-01-15"},
    {"id": "internvl3_78b", "display_name": "InternVL3 78B (Vision)",
     "family": "internlm", "params_total_b": 78, "params_active_b": 78,
     "context_window": 32768, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 80, "hidden_dim": 8192,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "MIT (LM은 Qwen 라이선스 종속)", "license_commercial_ok": True,
     "hf_repo": "OpenGVLab/InternVL3-78B", "release_date": "2025-04-11"},
    {"id": "internvl3_38b", "display_name": "InternVL3 38B (Vision)",
     "family": "internlm", "params_total_b": 38, "params_active_b": 38,
     "context_window": 32768, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "MIT (LM은 Qwen 라이선스 종속)", "license_commercial_ok": True,
     "hf_repo": "OpenGVLab/InternVL3-38B", "release_date": "2025-04-11"},

    # === Tsinghua MiniCPM ===
    {"id": "minicpm_4_8b", "display_name": "MiniCPM 4 8B (Edge)",
     "family": "openbmb", "params_total_b": 8, "params_active_b": 8,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "openbmb/MiniCPM4-8B", "release_date": "2025-06-06"},
    {"id": "minicpm_v_4_5", "display_name": "MiniCPM-V 4.5 8B (Vision)",
     "family": "openbmb", "params_total_b": 8, "params_active_b": 8,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 36, "hidden_dim": 4096,
     "modalities": ["text", "vision"], "capabilities": ["tool_use"],
     "license": "Apache-2.0 (가중치는 별도 검토)", "license_commercial_ok": True,
     "hf_repo": "openbmb/MiniCPM-V-4_5", "release_date": "2025-08-26"},

    # === Hugging Face SmolLM ===
    {"id": "smollm3_3b", "display_name": "SmolLM3 3B (Dual-mode)",
     "family": "smollm", "params_total_b": 3, "params_active_b": 3,
     "context_window": 65536, "num_attention_heads": 16, "num_kv_heads": 4,
     "num_layers": 36, "hidden_dim": 2048,
     "modalities": ["text"], "capabilities": ["reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "HuggingFaceTB/SmolLM3-3B", "release_date": "2025-07-08"},
    {"id": "smollm2_1_7b", "display_name": "SmolLM2 1.7B Instruct",
     "family": "smollm", "params_total_b": 1.7, "params_active_b": 1.7,
     "context_window": 8192, "num_attention_heads": 32, "num_kv_heads": 32,
     "num_layers": 24, "hidden_dim": 2048,
     "modalities": ["text"], "capabilities": [],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "HuggingFaceTB/SmolLM2-1.7B-Instruct", "release_date": "2024-11-01"},

    # === Llama 3.2 1B (소형) ===
    {"id": "llama_3_2_1b", "display_name": "Llama 3.2 1B Instruct",
     "family": "llama", "params_total_b": 1.23, "params_active_b": 1.23,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 16, "hidden_dim": 2048,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Llama 3.2 Community", "license_commercial_ok": True,
     "hf_repo": "meta-llama/Llama-3.2-1B-Instruct", "release_date": "2024-09-25"},

    # === Gemma 3 작은 변형 ===
    {"id": "gemma_3_1b", "display_name": "Gemma 3 1B IT",
     "family": "gemma", "params_total_b": 1.0, "params_active_b": 1.0,
     "context_window": 32768, "num_attention_heads": 4, "num_kv_heads": 1,
     "num_layers": 26, "hidden_dim": 1152,
     "modalities": ["text"], "capabilities": [],
     "license": "Gemma Terms of Use", "license_commercial_ok": True,
     "hf_repo": "google/gemma-3-1b-it", "release_date": "2025-03-12"},
    {"id": "gemma_3_270m", "display_name": "Gemma 3 270M (Tiny)",
     "family": "gemma", "params_total_b": 0.27, "params_active_b": 0.27,
     "context_window": 32768, "num_attention_heads": 4, "num_kv_heads": 1,
     "num_layers": 18, "hidden_dim": 640,
     "modalities": ["text"], "capabilities": [],
     "license": "Gemma Terms of Use", "license_commercial_ok": True,
     "hf_repo": "google/gemma-3-270m-it", "release_date": "2025-08-14"},

    # === TII Falcon 3 ===
    {"id": "falcon3_10b", "display_name": "Falcon 3 10B Instruct",
     "family": "falcon", "params_total_b": 10, "params_active_b": 10,
     "context_window": 32768, "num_attention_heads": 12, "num_kv_heads": 4,
     "num_layers": 40, "hidden_dim": 3072,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Falcon-LLM License", "license_commercial_ok": True,
     "hf_repo": "tiiuae/Falcon3-10B-Instruct", "release_date": "2024-12-17"},
    {"id": "falcon3_7b", "display_name": "Falcon 3 7B Instruct",
     "family": "falcon", "params_total_b": 7, "params_active_b": 7,
     "context_window": 32768, "num_attention_heads": 12, "num_kv_heads": 4,
     "num_layers": 28, "hidden_dim": 3072,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Falcon-LLM License", "license_commercial_ok": True,
     "hf_repo": "tiiuae/Falcon3-7B-Instruct", "release_date": "2024-12-17"},

    # === AI2 OLMo 2 (fully open) ===
    {"id": "olmo2_13b", "display_name": "OLMo 2 13B Instruct (Fully Open)",
     "family": "olmo", "params_total_b": 13.7, "params_active_b": 13.7,
     "context_window": 4096, "num_attention_heads": 40, "num_kv_heads": 40,
     "num_layers": 40, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": [],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "allenai/OLMo-2-1124-13B-Instruct", "release_date": "2024-11-26"},
    {"id": "olmo2_32b", "display_name": "OLMo 2 32B Instruct (Fully Open)",
     "family": "olmo", "params_total_b": 32, "params_active_b": 32,
     "context_window": 4096, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": [],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "allenai/OLMo-2-0325-32B-Instruct", "release_date": "2025-03-13"},

    # === Cohere Command A / Aya (CC-BY-NC, 비상용) ===
    {"id": "command_a_111b", "display_name": "Command A 111B (Enterprise)",
     "family": "cohere", "params_total_b": 111, "params_active_b": 111,
     "context_window": 256000, "num_attention_heads": 96, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 12288,
     "modalities": ["text"], "capabilities": ["tool_use", "json_mode"],
     "license": "CC-BY-NC + Cohere AUP", "license_commercial_ok": False,
     "hf_repo": "CohereLabs/c4ai-command-a-03-2025", "release_date": "2025-03-13"},
    {"id": "aya_expanse_32b", "display_name": "Aya Expanse 32B (다국어 23개)",
     "family": "cohere", "params_total_b": 32, "params_active_b": 32,
     "context_window": 128000, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 8192,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "CC-BY-NC", "license_commercial_ok": False,
     "hf_repo": "CohereLabs/aya-expanse-32b", "release_date": "2024-10-24"},
    {"id": "aya_expanse_8b", "display_name": "Aya Expanse 8B (다국어)",
     "family": "cohere", "params_total_b": 8, "params_active_b": 8,
     "context_window": 8192, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "CC-BY-NC", "license_commercial_ok": False,
     "hf_repo": "CohereLabs/aya-expanse-8b", "release_date": "2024-10-24"},
    {"id": "aya_vision_32b", "display_name": "Aya Vision 32B (다국어 비전)",
     "family": "cohere", "params_total_b": 32, "params_active_b": 32,
     "context_window": 16384, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 8192,
     "modalities": ["text", "vision"], "capabilities": ["ko_native"],
     "license": "CC-BY-NC", "license_commercial_ok": False,
     "hf_repo": "CohereLabs/aya-vision-32b", "release_date": "2025-03-04"},
    {"id": "aya_vision_8b", "display_name": "Aya Vision 8B (다국어 비전)",
     "family": "cohere", "params_total_b": 8, "params_active_b": 8,
     "context_window": 16384, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text", "vision"], "capabilities": ["ko_native"],
     "license": "CC-BY-NC", "license_commercial_ok": False,
     "hf_repo": "CohereLabs/aya-vision-8b", "release_date": "2025-03-04"},

    # === Mistral Pixtral Large (비상용 MRL) ===
    {"id": "pixtral_large_124b", "display_name": "Pixtral Large 124B (Vision)",
     "family": "mistral", "params_total_b": 124, "params_active_b": 124,
     "context_window": 128000, "num_attention_heads": 96, "num_kv_heads": 8,
     "num_layers": 88, "hidden_dim": 12288,
     "modalities": ["text", "vision"], "capabilities": [],
     "license": "Mistral Research License (비상용)", "license_commercial_ok": False,
     "hf_repo": "mistralai/Pixtral-Large-Instruct-2411", "release_date": "2024-11-18"},

    # === AI21 Jamba (Hybrid SSM-Transformer MoE, 256K) ===
    {"id": "jamba_1_5_large", "display_name": "Jamba 1.5 Large 398B (A94B, Hybrid)",
     "family": "ai21", "params_total_b": 398, "params_active_b": 94,
     "context_window": 256000, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 72, "hidden_dim": 8192,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Jamba Open Model License", "license_commercial_ok": True,
     "hf_repo": "ai21labs/AI21-Jamba-1.5-Large", "release_date": "2024-08-22"},
    {"id": "jamba_1_5_mini", "display_name": "Jamba 1.5 Mini 52B (A12B, Hybrid)",
     "family": "ai21", "params_total_b": 52, "params_active_b": 12,
     "context_window": 256000, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "Jamba Open Model License", "license_commercial_ok": True,
     "hf_repo": "ai21labs/AI21-Jamba-1.5-Mini", "release_date": "2024-08-22"},

    # === Snowflake Arctic ===
    {"id": "arctic_480b", "display_name": "Snowflake Arctic 480B (A17B, Dense-MoE)",
     "family": "snowflake", "params_total_b": 480, "params_active_b": 17,
     "context_window": 4096, "num_attention_heads": 56, "num_kv_heads": 8,
     "num_layers": 35, "hidden_dim": 7168,
     "modalities": ["text"], "capabilities": [],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Snowflake/snowflake-arctic-instruct", "release_date": "2024-04-24"},

    # === NVIDIA Nemotron ===
    {"id": "llama_3_1_nemotron_70b",
     "display_name": "Llama-3.1-Nemotron 70B (RLHF tuned)",
     "family": "nvidia", "params_total_b": 70, "params_active_b": 70,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 80, "hidden_dim": 8192,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "NVIDIA Open Model + Llama 3.1 Community",
     "license_commercial_ok": True,
     "hf_repo": "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
     "release_date": "2024-10-15"},

    # === Reka AI ===
    {"id": "reka_flash_3", "display_name": "Reka Flash 3 21B (Reasoning)",
     "family": "reka", "params_total_b": 21, "params_active_b": 21,
     "context_window": 131072, "num_attention_heads": 48, "num_kv_heads": 8,
     "num_layers": 40, "hidden_dim": 6144,
     "modalities": ["text"], "capabilities": ["reasoning_mode"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "RekaAI/reka-flash-3", "release_date": "2025-03-13"},

    # === 추론 특화 (QwQ, R1-Distill 시리즈) ===
    {"id": "qwq_32b", "display_name": "QwQ-32B (Qwen Reasoning)",
     "family": "qwen", "params_total_b": 32.5, "params_active_b": 32.5,
     "context_window": 131072, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["reasoning_mode", "tool_use"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "Qwen/QwQ-32B", "release_date": "2025-03-06"},
    {"id": "r1_distill_llama_70b",
     "display_name": "DeepSeek-R1-Distill Llama 70B",
     "family": "deepseek", "params_total_b": 70, "params_active_b": 70,
     "context_window": 131072, "num_attention_heads": 64, "num_kv_heads": 8,
     "num_layers": 80, "hidden_dim": 8192,
     "modalities": ["text"], "capabilities": ["reasoning_mode"],
     "license": "MIT + Llama 3.3 Community", "license_commercial_ok": True,
     "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
     "release_date": "2025-01-20"},
    {"id": "r1_distill_qwen_32b",
     "display_name": "DeepSeek-R1-Distill Qwen 32B",
     "family": "deepseek", "params_total_b": 32.5, "params_active_b": 32.5,
     "context_window": 131072, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 64, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["reasoning_mode"],
     "license": "MIT + Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
     "release_date": "2025-01-20"},
    {"id": "r1_distill_qwen_14b",
     "display_name": "DeepSeek-R1-Distill Qwen 14B",
     "family": "deepseek", "params_total_b": 14.8, "params_active_b": 14.8,
     "context_window": 131072, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 48, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["reasoning_mode"],
     "license": "MIT + Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
     "release_date": "2025-01-20"},

    # === 한국어 추가 (Kakao Kanana, Trillion Labs) ===
    {"id": "kanana_2_30b_a3b",
     "display_name": "Kanana 2 30B (A3B MoE, Agentic)",
     "family": "kakao", "params_total_b": 30, "params_active_b": 3,
     "context_window": 65536, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 48, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["ko_native", "tool_use"],
     "license": "Kanana Community License", "license_commercial_ok": True,
     "hf_repo": "kakaocorp/kanana-2-30b-a3b-instruct",
     "release_date": "2026-01-15"},
    {"id": "kanana_1_5_8b", "display_name": "Kanana 1.5 8B (한영)",
     "family": "kakao", "params_total_b": 8, "params_active_b": 8,
     "context_window": 32768, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "Kanana Community License", "license_commercial_ok": True,
     "hf_repo": "kakaocorp/kanana-1.5-8b-instruct-2505",
     "release_date": "2025-05-01"},
    {"id": "kanana_1_5_v_3b",
     "display_name": "Kanana 1.5 V 3B (한영 비전, On-device)",
     "family": "kakao", "params_total_b": 3, "params_active_b": 3,
     "context_window": 8192, "num_attention_heads": 24, "num_kv_heads": 8,
     "num_layers": 30, "hidden_dim": 3072,
     "modalities": ["text", "vision"], "capabilities": ["ko_native"],
     "license": "Kanana Community License", "license_commercial_ok": True,
     "hf_repo": "kakaocorp/kanana-1.5-v-3b-instruct",
     "release_date": "2025-05-01"},
    {"id": "kanana_nano_2_1b",
     "display_name": "Kanana Nano 2.1B (On-device)",
     "family": "kakao", "params_total_b": 2.1, "params_active_b": 2.1,
     "context_window": 8192, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 24, "hidden_dim": 2048,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "Kanana Community License", "license_commercial_ok": True,
     "hf_repo": "kakaocorp/kanana-nano-2.1b-instruct",
     "release_date": "2025-02-01"},
    {"id": "tri_21b", "display_name": "Tri 21B (한영일중)",
     "family": "trillion", "params_total_b": 21, "params_active_b": 21,
     "context_window": 32768, "num_attention_heads": 40, "num_kv_heads": 8,
     "num_layers": 56, "hidden_dim": 5120,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "trillionlabs/Tri-21B", "release_date": "2025-09-01"},
    {"id": "trillion_7b", "display_name": "Trillion 7B preview (한영일중)",
     "family": "trillion", "params_total_b": 7.76, "params_active_b": 7.76,
     "context_window": 8192, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["ko_native"],
     "license": "Apache-2.0", "license_commercial_ok": True,
     "hf_repo": "trillionlabs/Trillion-7B-preview",
     "release_date": "2025-04-01"},

    # === Phi-3.5-MoE ===
    {"id": "phi_3_5_moe", "display_name": "Phi-3.5-MoE 41.9B (A6.6B)",
     "family": "phi", "params_total_b": 41.9, "params_active_b": 6.6,
     "context_window": 131072, "num_attention_heads": 32, "num_kv_heads": 8,
     "num_layers": 32, "hidden_dim": 4096,
     "modalities": ["text"], "capabilities": ["tool_use"],
     "license": "MIT", "license_commercial_ok": True,
     "hf_repo": "microsoft/Phi-3.5-MoE-instruct", "release_date": "2024-08-20"},
]


BENCHMARKS = [
    # Qwen3-32B
    ("qwen3_32b", "mmlu_pro", 65.5, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "gpqa", 47.5, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "math", 73.5, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "humaneval", 88.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "livecodebench", 41.5, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_32b", "ifeval", 83.2, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),

    # Qwen3-Coder-32B
    ("qwen3_coder_32b", "livecodebench", 64.2, "official", "measured", "2025-07-15",
     "https://qwenlm.github.io/blog/qwen3-coder/"),
    ("qwen3_coder_32b", "humaneval", 92.1, "official", "measured", "2025-07-15",
     "https://qwenlm.github.io/blog/qwen3-coder/"),
    ("qwen3_coder_32b", "swe_bench_verified", 41.5, "official", "measured", "2025-07-15",
     "https://qwenlm.github.io/blog/qwen3-coder/"),
    ("qwen3_coder_32b", "bigcodebench", 55.0, "official", "measured", "2025-07-15",
     "https://qwenlm.github.io/blog/qwen3-coder/"),

    # Llama 3.3 70B
    ("llama_3_3_70b", "mmlu_pro", 68.9, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),
    ("llama_3_3_70b", "humaneval", 88.4, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),
    ("llama_3_3_70b", "math", 77.0, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),
    ("llama_3_3_70b", "ifeval", 92.1, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),
    ("llama_3_3_70b", "gsm8k", 95.6, "official", "measured", "2024-12-06",
     "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"),

    # GPT-OSS 120B
    ("gpt_oss_120b", "mmlu_pro", 70.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_120b", "gpqa", 56.4, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_120b", "humaneval", 88.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_120b", "math", 80.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),

    # GPT-OSS 20B
    ("gpt_oss_20b", "mmlu_pro", 60.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_20b", "humaneval", 80.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),

    # DeepSeek V3.1
    ("deepseek_v3_1", "mmlu_pro", 75.9, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "humaneval", 92.0, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "swe_bench_verified", 46.0, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "math", 84.5, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "gpqa", 68.4, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),
    ("deepseek_v3_1", "livecodebench", 56.0, "official", "measured", "2025-08-21",
     "https://api-docs.deepseek.com/news/news250821"),

    # EXAONE 3.5 32B (한국어 강점)
    ("exaone_3_5_32b", "kmmlu", 51.2, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-32B-Instruct"),
    ("exaone_3_5_32b", "logickor", 9.25, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-32B-Instruct"),
    ("exaone_3_5_32b", "hae_rae", 80.4, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-32B-Instruct"),
    ("exaone_3_5_32b", "mmlu_pro", 49.9, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-32B-Instruct"),

    # EXAONE 3.5 7.8B
    ("exaone_3_5_7_8b", "kmmlu", 48.1, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),
    ("exaone_3_5_7_8b", "logickor", 8.25, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),
    ("exaone_3_5_7_8b", "hae_rae", 75.0, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),

    # Solar Pro 22B
    ("solar_pro_22b", "kmmlu", 51.0, "official", "measured", "2024-09-11",
     "https://huggingface.co/upstage/solar-pro-preview-instruct"),
    ("solar_pro_22b", "mmlu_pro", 52.1, "official", "measured", "2024-09-11",
     "https://huggingface.co/upstage/solar-pro-preview-instruct"),

    # Gemma 3 27B
    ("gemma_3_27b", "mmlu_pro", 67.5, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-27b-it"),
    ("gemma_3_27b", "math", 89.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-27b-it"),
    ("gemma_3_27b", "mmmu", 64.9, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-27b-it"),
    ("gemma_3_27b", "doc_vqa", 85.6, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-27b-it"),

    # Phi-4
    ("phi_4", "mmlu_pro", 70.4, "official", "measured", "2024-12-12",
     "https://arxiv.org/abs/2412.08905"),
    ("phi_4", "math", 80.4, "official", "measured", "2024-12-12",
     "https://arxiv.org/abs/2412.08905"),
    ("phi_4", "humaneval", 82.6, "official", "measured", "2024-12-12",
     "https://arxiv.org/abs/2412.08905"),

    # Mistral Small 3
    ("mistral_small_3", "mmlu_pro", 65.0, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),
    ("mistral_small_3", "humaneval", 84.8, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),

    # Qwen3-Coder-32B preferred bonus check (also has json/tool already)
    # Qwen2.5-VL-32B - vision
    ("qwen2_5_vl_32b", "mmmu", 67.0, "official", "measured", "2025-03-24",
     "https://huggingface.co/Qwen/Qwen2.5-VL-32B-Instruct"),
    ("qwen2_5_vl_32b", "doc_vqa", 88.4, "official", "measured", "2025-03-24",
     "https://huggingface.co/Qwen/Qwen2.5-VL-32B-Instruct"),
    ("qwen2_5_vl_32b", "ocr_bench", 83.0, "official", "measured", "2025-03-24",
     "https://huggingface.co/Qwen/Qwen2.5-VL-32B-Instruct"),
    ("qwen2_5_vl_32b", "chart_qa", 81.0, "official", "measured", "2025-03-24",
     "https://huggingface.co/Qwen/Qwen2.5-VL-32B-Instruct"),

    # === Mistral Small 3 (보강) ===
    ("mistral_small_3", "math", 70.6, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),
    ("mistral_small_3", "gsm8k", 90.0, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),
    ("mistral_small_3", "ifeval", 78.0, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),
    ("mistral_small_3", "gpqa", 45.3, "official", "measured", "2025-01-30",
     "https://mistral.ai/news/mistral-small-3/"),

    # === GPT-OSS 20B (보강) ===
    ("gpt_oss_20b", "gpqa", 39.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_20b", "math", 67.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),
    ("gpt_oss_20b", "mmlu_pro", 60.0, "official", "measured", "2025-08-05",
     "https://openai.com/index/gpt-oss/"),

    # === EXAONE 4.0 32B (LG, 2025-07) ===
    ("exaone_4_32b", "mmlu_pro", 70.8, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "kmmlu", 67.5, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "hae_rae", 84.9, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "logickor", 9.50, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "math", 97.4, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "aime", 56.7, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "livecodebench", 56.7, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "bfcl_v3", 79.5, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),
    ("exaone_4_32b", "ifeval", 89.8, "official", "measured", "2025-07-15",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-4.0-32B"),

    # === EXAONE Deep 32B / 7.8B / 2.4B (reasoning) ===
    ("exaone_deep_32b", "aime", 90.0, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-32B"),
    ("exaone_deep_32b", "math", 95.7, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-32B"),
    ("exaone_deep_32b", "gpqa_diamond", 66.1, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-32B"),
    ("exaone_deep_32b", "livecodebench", 59.5, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-32B"),
    ("exaone_deep_7_8b", "aime", 78.3, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-7.8B"),
    ("exaone_deep_7_8b", "math", 91.0, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-7.8B"),
    ("exaone_deep_7_8b", "gpqa_diamond", 56.4, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-7.8B"),
    ("exaone_deep_2_4b", "aime", 47.0, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-2.4B"),
    ("exaone_deep_2_4b", "math", 81.0, "official", "measured", "2025-03-18",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-Deep-2.4B"),

    # === SKT A.X 4.0 (한국어) ===
    ("ax_4_72b", "kmmlu", 78.3, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "hae_rae", 85.7, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "ifeval", 81.5, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "mmlu_pro", 70.0, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "math", 76.3, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_72b", "humaneval", 76.3, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0"),
    ("ax_4_light_7b", "kmmlu", 65.0, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0-Light"),
    ("ax_4_light_7b", "hae_rae", 78.0, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0-Light"),
    ("ax_4_light_7b", "ifeval", 75.0, "official", "measured", "2025-07-03",
     "https://huggingface.co/skt/A.X-4.0-Light"),

    # === HyperCLOVA SEED (한국어) ===
    ("hyperclovax_seed_text_1_5b", "kmmlu", 45.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B"),
    ("hyperclovax_seed_text_1_5b", "hae_rae", 70.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-1.5B"),
    ("hyperclovax_seed_text_0_5b", "hae_rae", 55.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Text-Instruct-0.5B"),
    ("hyperclovax_seed_vision_3b", "mmmu", 47.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B"),
    ("hyperclovax_seed_vision_3b", "ocr_bench", 75.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B"),
    ("hyperclovax_seed_vision_3b", "doc_vqa", 70.0, "official", "measured", "2025-04-24",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B"),
    ("hyperclovax_seed_think_14b", "kmmlu", 65.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-14B"),
    ("hyperclovax_seed_think_14b", "hae_rae", 85.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-14B"),
    ("hyperclovax_seed_think_14b", "math", 85.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-14B"),
    ("hyperclovax_seed_think_14b", "aime", 60.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/naver-hyperclovax/HyperCLOVAX-SEED-Think-14B"),

    # === Qwen3-Coder MoE 변형 ===
    ("qwen3_coder_30b_a3b", "livecodebench", 33.9, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "humaneval", 74.4, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "swe_bench_verified", 51.6, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "bfcl_v3", 70.0, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "mmlu_pro", 79.0, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_30b_a3b", "bigcodebench", 50.0, "official", "measured", "2025-07-30",
     "https://huggingface.co/Qwen/Qwen3-Coder-30B-A3B-Instruct"),
    ("qwen3_coder_480b_a35b", "livecodebench", 51.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),
    ("qwen3_coder_480b_a35b", "humaneval", 91.5, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),
    ("qwen3_coder_480b_a35b", "swe_bench_verified", 67.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),
    ("qwen3_coder_480b_a35b", "bfcl_v3", 84.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),
    ("qwen3_coder_480b_a35b", "bigcodebench", 65.0, "official", "measured", "2025-07-22",
     "https://huggingface.co/Qwen/Qwen3-Coder-480B-A35B-Instruct"),

    # === Qwen3-VL 시리즈 ===
    ("qwen3_vl_32b", "mmmu", 68.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_32b", "doc_vqa", 89.2, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_32b", "ocr_bench", 88.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_32b", "chart_qa", 87.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_32b", "mathvista", 73.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-32B-Instruct"),
    ("qwen3_vl_30b_a3b", "mmmu", 65.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-30B-A3B-Instruct"),
    ("qwen3_vl_30b_a3b", "ocr_bench", 85.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-30B-A3B-Instruct"),
    ("qwen3_vl_30b_a3b", "doc_vqa", 89.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-30B-A3B-Instruct"),
    ("qwen3_vl_30b_a3b", "chart_qa", 84.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-30B-A3B-Instruct"),
    ("qwen3_vl_8b", "mmmu", 58.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-8B-Instruct"),
    ("qwen3_vl_8b", "doc_vqa", 83.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-8B-Instruct"),
    ("qwen3_vl_8b", "ocr_bench", 78.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-8B-Instruct"),
    ("qwen3_vl_4b", "mmmu", 50.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-4B-Instruct"),
    ("qwen3_vl_4b", "doc_vqa", 78.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-4B-Instruct"),
    ("qwen3_vl_4b", "ocr_bench", 72.0, "official", "measured", "2025-10-04",
     "https://huggingface.co/Qwen/Qwen3-VL-4B-Instruct"),

    # === Qwen3-Omni ===
    ("qwen3_omni_30b_a3b", "mmlu_pro", 65.0, "official", "measured", "2025-09-15",
     "https://huggingface.co/Qwen/Qwen3-Omni-30B-A3B-Instruct"),
    ("qwen3_omni_30b_a3b", "mmmu", 60.0, "official", "measured", "2025-09-15",
     "https://huggingface.co/Qwen/Qwen3-Omni-30B-A3B-Instruct"),

    # === DeepSeek V3.1-Terminus / V3.2-Exp ===
    ("deepseek_v3_1_terminus", "mmlu_pro", 84.8, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "gpqa_diamond", 82.4, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "math", 90.6, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "livecodebench", 73.7, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "swe_bench_verified", 66.0, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "aime", 88.4, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "humaneval", 92.0, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_1_terminus", "bfcl_v3", 80.0, "official", "measured", "2025-09-22",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus"),
    ("deepseek_v3_2_exp", "mmlu_pro", 85.0, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),
    ("deepseek_v3_2_exp", "math", 90.5, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),
    ("deepseek_v3_2_exp", "livecodebench", 74.0, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),
    ("deepseek_v3_2_exp", "ruler", 92.0, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),
    ("deepseek_v3_2_exp", "longbench_v2", 50.0, "official", "measured", "2025-09-29",
     "https://huggingface.co/deepseek-ai/DeepSeek-V3.2-Exp"),

    # === Magistral / Devstral ===
    ("magistral_small_24b", "aime", 70.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("magistral_small_24b", "math", 92.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("magistral_small_24b", "mmlu_pro", 65.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("magistral_small_24b", "gpqa_diamond", 60.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("magistral_small_24b", "mmmu", 58.0, "official", "measured", "2025-09-01",
     "https://mistral.ai/news/magistral/"),
    ("devstral_small_24b", "swe_bench_verified", 53.6, "official", "measured", "2025-07-01",
     "https://mistral.ai/news/devstral/"),
    ("devstral_small_24b", "humaneval", 80.0, "official", "measured", "2025-07-01",
     "https://mistral.ai/news/devstral/"),
    ("devstral_small_24b", "livecodebench", 42.0, "official", "measured", "2025-07-01",
     "https://mistral.ai/news/devstral/"),
    ("devstral_small_24b", "bigcodebench", 48.0, "official", "measured", "2025-07-01",
     "https://mistral.ai/news/devstral/"),

    # === GLM-4.5 Air ===
    ("glm_4_5_air_106b", "mmlu_pro", 80.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "humaneval", 92.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "gpqa", 64.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "math", 88.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "bfcl_v3", 70.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),
    ("glm_4_5_air_106b", "swe_bench_verified", 50.0, "official", "measured", "2025-07-28",
     "https://huggingface.co/zai-org/GLM-4.5-Air"),

    # === MiniMax-M1 (long context) ===
    ("minimax_m1_80k", "mmlu_pro", 76.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "math", 81.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "livecodebench", 53.6, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "gpqa_diamond", 70.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "ruler", 95.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "longbench_v2", 56.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),
    ("minimax_m1_80k", "niah", 100.0, "official", "measured", "2025-06-17",
     "https://huggingface.co/MiniMaxAI/MiniMax-M1-80k"),

    # === Kimi K2 ===
    ("kimi_k2", "livecodebench", 53.7, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "swe_bench_verified", 65.8, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "humaneval", 92.0, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "math", 97.4, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "bfcl_v3", 76.5, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "aime", 49.5, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "mmlu_pro", 81.1, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),
    ("kimi_k2", "gpqa", 65.0, "official", "measured", "2025-07-11",
     "https://huggingface.co/moonshotai/Kimi-K2-Instruct"),

    # === Granite 4.1 ===
    ("granite_4_1_8b", "mmlu_pro", 50.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),
    ("granite_4_1_8b", "humaneval", 80.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),
    ("granite_4_1_8b", "ifeval", 80.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),
    ("granite_4_1_8b", "math", 60.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),
    ("granite_4_1_8b", "bfcl_v3", 65.0, "official", "measured", "2025-11-01",
     "https://huggingface.co/ibm-granite/granite-4.1-8b"),

    # === Phi-4 후속 ===
    ("phi_4_mini", "mmlu_pro", 52.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_mini", "math", 71.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_mini", "humaneval", 73.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_mini", "bfcl_v3", 70.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_mini", "ifeval", 75.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-mini-instruct"),
    ("phi_4_multimodal", "mmmu", 55.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-multimodal-instruct"),
    ("phi_4_multimodal", "doc_vqa", 90.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-multimodal-instruct"),
    ("phi_4_multimodal", "chart_qa", 80.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-multimodal-instruct"),
    ("phi_4_multimodal", "ocr_bench", 75.0, "official", "measured", "2025-02-26",
     "https://huggingface.co/microsoft/Phi-4-multimodal-instruct"),
    ("phi_4_mini_reasoning", "math", 95.0, "official", "measured", "2025-04-30",
     "https://huggingface.co/microsoft/Phi-4-mini-reasoning"),
    ("phi_4_mini_reasoning", "aime", 50.0, "official", "measured", "2025-04-30",
     "https://huggingface.co/microsoft/Phi-4-mini-reasoning"),
    ("phi_4_mini_reasoning", "gpqa_diamond", 47.0, "official", "measured", "2025-04-30",
     "https://huggingface.co/microsoft/Phi-4-mini-reasoning"),

    # === Gemma 3 4B ===
    ("gemma_3_4b", "mmlu_pro", 45.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),
    ("gemma_3_4b", "humaneval", 71.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),
    ("gemma_3_4b", "math", 50.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),
    ("gemma_3_4b", "mmmu", 48.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),
    ("gemma_3_4b", "doc_vqa", 75.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-4b-it"),

    # === Gemma 3 12B 보강 ===
    ("gemma_3_12b", "mmlu_pro", 60.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-12b-it"),
    ("gemma_3_12b", "humaneval", 78.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-12b-it"),
    ("gemma_3_12b", "math", 75.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-12b-it"),
    ("gemma_3_12b", "mmmu", 58.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-12b-it"),

    # === 기존 모델 보강: Qwen3-8B/14B/4B ===
    ("qwen3_4b", "mmlu_pro", 50.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_4b", "math", 65.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_4b", "humaneval", 70.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_8b", "mmlu_pro", 56.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_8b", "math", 70.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_8b", "humaneval", 78.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_14b", "mmlu_pro", 60.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_14b", "math", 72.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),
    ("qwen3_14b", "humaneval", 84.0, "official", "measured", "2025-04-29",
     "https://qwenlm.github.io/blog/qwen3/"),

    # === Llama 4 Scout 17B 보강 ===
    ("llama_4_scout_17b", "mmlu_pro", 74.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "humaneval", 85.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "math", 80.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "mmmu", 69.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "doc_vqa", 88.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),
    ("llama_4_scout_17b", "ifeval", 86.0, "official", "measured", "2025-04-05",
     "https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct"),

    # === EXAONE 3.5 7.8B 보강 ===
    ("exaone_3_5_7_8b", "mmlu_pro", 38.0, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),
    ("exaone_3_5_7_8b", "ifeval", 78.0, "official", "measured", "2024-12-09",
     "https://huggingface.co/LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"),

    # === Llama 3.2 3B 보강 ===
    ("llama_3_2_3b", "mmlu_pro", 38.0, "official", "measured", "2024-09-25",
     "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"),
    ("llama_3_2_3b", "humaneval", 60.0, "official", "measured", "2024-09-25",
     "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"),
    ("llama_3_2_3b", "ifeval", 77.0, "official", "measured", "2024-09-25",
     "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct"),

    # === Mixtral 8x22B 보강 ===
    ("mixtral_8x22b", "mmlu_pro", 50.0, "official", "measured", "2024-04-17",
     "https://mistral.ai/news/mixtral-8x22b/"),
    ("mixtral_8x22b", "humaneval", 75.0, "official", "measured", "2024-04-17",
     "https://mistral.ai/news/mixtral-8x22b/"),
    ("mixtral_8x22b", "math", 41.8, "official", "measured", "2024-04-17",
     "https://mistral.ai/news/mixtral-8x22b/"),

    # === Solar Pro 22B 보강 ===
    ("solar_pro_22b", "ifeval", 84.0, "official", "measured", "2024-09-11",
     "https://huggingface.co/upstage/solar-pro-preview-instruct"),
    ("solar_pro_22b", "gsm8k", 89.0, "official", "measured", "2024-09-11",
     "https://huggingface.co/upstage/solar-pro-preview-instruct"),

    # === KULLM 3 보강 ===
    ("kullm3", "kmmlu", 35.0, "official", "measured", "2024-04-15",
     "https://huggingface.co/nlpai-lab/KULLM3"),
    ("kullm3", "hae_rae", 65.0, "official", "measured", "2024-04-15",
     "https://huggingface.co/nlpai-lab/KULLM3"),

    # ===== 신규 모델 벤치마크 =====
    # Hunyuan
    ("hunyuan_large", "mmlu_pro", 60.2, "official", "measured", "2024-11-05",
     "https://huggingface.co/tencent/Tencent-Hunyuan-Large"),
    ("hunyuan_large", "math", 69.8, "official", "measured", "2024-11-05",
     "https://huggingface.co/tencent/Tencent-Hunyuan-Large"),
    ("hunyuan_large", "humaneval", 71.4, "official", "measured", "2024-11-05",
     "https://huggingface.co/tencent/Tencent-Hunyuan-Large"),
    ("hunyuan_a13b", "mmlu_pro", 67.8, "official", "measured", "2025-06-27",
     "https://huggingface.co/tencent/Hunyuan-A13B-Instruct"),
    ("hunyuan_a13b", "math", 72.4, "official", "measured", "2025-06-27",
     "https://huggingface.co/tencent/Hunyuan-A13B-Instruct"),
    ("hunyuan_a13b", "gpqa", 49.1, "official", "measured", "2025-06-27",
     "https://huggingface.co/tencent/Hunyuan-A13B-Instruct"),
    ("hunyuan_a13b", "livecodebench", 44.7, "official", "measured", "2025-06-27",
     "https://huggingface.co/tencent/Hunyuan-A13B-Instruct"),

    # Yi
    ("yi_1_5_34b", "mmlu_pro", 50.0, "official", "measured", "2024-05-13",
     "https://huggingface.co/01-ai/Yi-1.5-34B-Chat"),
    ("yi_1_5_34b", "math", 50.1, "official", "measured", "2024-05-13",
     "https://huggingface.co/01-ai/Yi-1.5-34B-Chat"),
    ("yi_1_5_34b", "humaneval", 75.2, "official", "measured", "2024-05-13",
     "https://huggingface.co/01-ai/Yi-1.5-34B-Chat"),
    ("yi_1_5_9b", "mmlu_pro", 45.0, "official", "measured", "2024-05-13",
     "https://huggingface.co/01-ai/Yi-1.5-9B-Chat"),
    ("yi_1_5_9b", "math", 30.9, "official", "measured", "2024-05-13",
     "https://huggingface.co/01-ai/Yi-1.5-9B-Chat"),
    ("yi_1_5_9b", "humaneval", 64.6, "official", "measured", "2024-05-13",
     "https://huggingface.co/01-ai/Yi-1.5-9B-Chat"),
    ("yi_coder_9b", "humaneval", 85.4, "official", "measured", "2024-09-04",
     "https://huggingface.co/01-ai/Yi-Coder-9B-Chat"),
    ("yi_coder_9b", "livecodebench", 23.4, "official", "measured", "2024-09-04",
     "https://huggingface.co/01-ai/Yi-Coder-9B-Chat"),

    # InternLM/InternVL
    ("internlm3_8b", "mmlu_pro", 50.0, "official", "measured", "2025-01-15",
     "https://huggingface.co/internlm/internlm3-8b-instruct"),
    ("internlm3_8b", "math", 83.0, "official", "measured", "2025-01-15",
     "https://huggingface.co/internlm/internlm3-8b-instruct"),
    ("internlm3_8b", "gpqa", 37.4, "official", "measured", "2025-01-15",
     "https://huggingface.co/internlm/internlm3-8b-instruct"),
    ("internlm3_8b", "humaneval", 82.3, "official", "measured", "2025-01-15",
     "https://huggingface.co/internlm/internlm3-8b-instruct"),
    ("internvl3_78b", "mmmu", 72.2, "official", "measured", "2025-04-11",
     "https://huggingface.co/OpenGVLab/InternVL3-78B"),
    ("internvl3_78b", "mathvista", 79.0, "official", "measured", "2025-04-11",
     "https://huggingface.co/OpenGVLab/InternVL3-78B"),
    ("internvl3_78b", "ocr_bench", 90.6, "official", "measured", "2025-04-11",
     "https://huggingface.co/OpenGVLab/InternVL3-78B"),
    ("internvl3_38b", "mmmu", 70.1, "official", "measured", "2025-04-11",
     "https://huggingface.co/OpenGVLab/InternVL3-38B"),
    ("internvl3_38b", "mathvista", 75.1, "official", "measured", "2025-04-11",
     "https://huggingface.co/OpenGVLab/InternVL3-38B"),
    ("internvl3_38b", "ocr_bench", 88.6, "official", "measured", "2025-04-11",
     "https://huggingface.co/OpenGVLab/InternVL3-38B"),

    # MiniCPM
    ("minicpm_4_8b", "mmlu_pro", 55.0, "official", "measured", "2025-06-06",
     "https://huggingface.co/openbmb/MiniCPM4-8B"),
    ("minicpm_4_8b", "math", 60.4, "official", "measured", "2025-06-06",
     "https://huggingface.co/openbmb/MiniCPM4-8B"),
    ("minicpm_v_4_5", "mmmu", 60.3, "official", "measured", "2025-08-26",
     "https://huggingface.co/openbmb/MiniCPM-V-4_5"),
    ("minicpm_v_4_5", "mathvista", 78.4, "official", "measured", "2025-08-26",
     "https://huggingface.co/openbmb/MiniCPM-V-4_5"),

    # SmolLM
    ("smollm3_3b", "mmlu_pro", 40.0, "official", "measured", "2025-07-08",
     "https://huggingface.co/HuggingFaceTB/SmolLM3-3B"),
    ("smollm3_3b", "math", 38.7, "official", "measured", "2025-07-08",
     "https://huggingface.co/HuggingFaceTB/SmolLM3-3B"),
    ("smollm3_3b", "gsm8k", 73.7, "official", "measured", "2025-07-08",
     "https://huggingface.co/HuggingFaceTB/SmolLM3-3B"),
    ("smollm3_3b", "humaneval", 51.2, "official", "measured", "2025-07-08",
     "https://huggingface.co/HuggingFaceTB/SmolLM3-3B"),
    ("smollm2_1_7b", "mmlu_pro", 30.0, "official", "measured", "2024-11-01",
     "https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct"),
    ("smollm2_1_7b", "gsm8k", 31.0, "official", "measured", "2024-11-01",
     "https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct"),

    # Llama 3.2 1B
    ("llama_3_2_1b", "mmlu_pro", 28.0, "official", "measured", "2024-09-25",
     "https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct"),
    ("llama_3_2_1b", "math", 30.6, "official", "measured", "2024-09-25",
     "https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct"),
    ("llama_3_2_1b", "gsm8k", 44.4, "official", "measured", "2024-09-25",
     "https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct"),

    # Gemma 3 small
    ("gemma_3_1b", "mmlu_pro", 25.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-1b-it"),
    ("gemma_3_1b", "gsm8k", 35.0, "official", "measured", "2025-03-12",
     "https://huggingface.co/google/gemma-3-1b-it"),

    # Falcon 3
    ("falcon3_10b", "mmlu_pro", 50.0, "official", "measured", "2024-12-17",
     "https://huggingface.co/tiiuae/Falcon3-10B-Instruct"),
    ("falcon3_10b", "humaneval", 73.8, "official", "measured", "2024-12-17",
     "https://huggingface.co/tiiuae/Falcon3-10B-Instruct"),
    ("falcon3_10b", "math", 24.7, "official", "measured", "2024-12-17",
     "https://huggingface.co/tiiuae/Falcon3-10B-Instruct"),
    ("falcon3_7b", "mmlu_pro", 47.0, "official", "measured", "2024-12-17",
     "https://huggingface.co/tiiuae/Falcon3-7B-Instruct"),
    ("falcon3_7b", "humaneval", 70.1, "official", "measured", "2024-12-17",
     "https://huggingface.co/tiiuae/Falcon3-7B-Instruct"),
    ("falcon3_7b", "gsm8k", 79.1, "official", "measured", "2024-12-17",
     "https://huggingface.co/tiiuae/Falcon3-7B-Instruct"),

    # OLMo 2
    ("olmo2_13b", "mmlu_pro", 45.0, "official", "measured", "2024-11-26",
     "https://huggingface.co/allenai/OLMo-2-1124-13B-Instruct"),
    ("olmo2_13b", "humaneval", 60.4, "official", "measured", "2024-11-26",
     "https://huggingface.co/allenai/OLMo-2-1124-13B-Instruct"),
    ("olmo2_13b", "gsm8k", 77.5, "official", "measured", "2024-11-26",
     "https://huggingface.co/allenai/OLMo-2-1124-13B-Instruct"),
    ("olmo2_32b", "mmlu_pro", 55.0, "official", "measured", "2025-03-13",
     "https://huggingface.co/allenai/OLMo-2-0325-32B-Instruct"),
    ("olmo2_32b", "math", 53.6, "official", "measured", "2025-03-13",
     "https://huggingface.co/allenai/OLMo-2-0325-32B-Instruct"),
    ("olmo2_32b", "humaneval", 80.5, "official", "measured", "2025-03-13",
     "https://huggingface.co/allenai/OLMo-2-0325-32B-Instruct"),

    # Cohere Command A
    ("command_a_111b", "mmlu_pro", 56.5, "official", "measured", "2025-03-13",
     "https://huggingface.co/CohereLabs/c4ai-command-a-03-2025"),
    ("command_a_111b", "math", 80.0, "official", "measured", "2025-03-13",
     "https://huggingface.co/CohereLabs/c4ai-command-a-03-2025"),
    ("command_a_111b", "ifeval", 90.9, "official", "measured", "2025-03-13",
     "https://huggingface.co/CohereLabs/c4ai-command-a-03-2025"),
    ("command_a_111b", "humaneval", 84.1, "official", "measured", "2025-03-13",
     "https://huggingface.co/CohereLabs/c4ai-command-a-03-2025"),

    # Aya (한국어 포함)
    ("aya_expanse_32b", "kmmlu", 45.0, "official", "measured", "2024-10-24",
     "https://huggingface.co/CohereLabs/aya-expanse-32b"),
    ("aya_expanse_32b", "hae_rae", 70.0, "official", "measured", "2024-10-24",
     "https://huggingface.co/CohereLabs/aya-expanse-32b"),
    ("aya_expanse_32b", "math", 60.0, "official", "measured", "2024-10-24",
     "https://huggingface.co/CohereLabs/aya-expanse-32b"),
    ("aya_expanse_8b", "kmmlu", 38.0, "official", "measured", "2024-10-24",
     "https://huggingface.co/CohereLabs/aya-expanse-8b"),
    ("aya_expanse_8b", "hae_rae", 60.0, "official", "measured", "2024-10-24",
     "https://huggingface.co/CohereLabs/aya-expanse-8b"),
    ("aya_vision_32b", "mmmu", 52.0, "official", "measured", "2025-03-04",
     "https://huggingface.co/CohereLabs/aya-vision-32b"),
    ("aya_vision_8b", "mmmu", 45.0, "official", "measured", "2025-03-04",
     "https://huggingface.co/CohereLabs/aya-vision-8b"),

    # Pixtral Large
    ("pixtral_large_124b", "mmmu", 64.0, "official", "measured", "2024-11-18",
     "https://huggingface.co/mistralai/Pixtral-Large-Instruct-2411"),
    ("pixtral_large_124b", "mathvista", 69.4, "official", "measured", "2024-11-18",
     "https://huggingface.co/mistralai/Pixtral-Large-Instruct-2411"),
    ("pixtral_large_124b", "doc_vqa", 93.3, "official", "measured", "2024-11-18",
     "https://huggingface.co/mistralai/Pixtral-Large-Instruct-2411"),
    ("pixtral_large_124b", "chart_qa", 88.1, "official", "measured", "2024-11-18",
     "https://huggingface.co/mistralai/Pixtral-Large-Instruct-2411"),

    # Jamba 1.5
    ("jamba_1_5_large", "mmlu_pro", 65.0, "official", "measured", "2024-08-22",
     "https://huggingface.co/ai21labs/AI21-Jamba-1.5-Large"),
    ("jamba_1_5_large", "gsm8k", 87.0, "official", "measured", "2024-08-22",
     "https://huggingface.co/ai21labs/AI21-Jamba-1.5-Large"),
    ("jamba_1_5_large", "humaneval", 66.0, "official", "measured", "2024-08-22",
     "https://huggingface.co/ai21labs/AI21-Jamba-1.5-Large"),
    ("jamba_1_5_mini", "mmlu_pro", 50.0, "official", "measured", "2024-08-22",
     "https://huggingface.co/ai21labs/AI21-Jamba-1.5-Mini"),
    ("jamba_1_5_mini", "gsm8k", 75.8, "official", "measured", "2024-08-22",
     "https://huggingface.co/ai21labs/AI21-Jamba-1.5-Mini"),

    # Snowflake Arctic
    ("arctic_480b", "mmlu_pro", 50.0, "official", "measured", "2024-04-24",
     "https://huggingface.co/Snowflake/snowflake-arctic-instruct"),
    ("arctic_480b", "humaneval", 64.9, "official", "measured", "2024-04-24",
     "https://huggingface.co/Snowflake/snowflake-arctic-instruct"),
    ("arctic_480b", "ifeval", 52.4, "official", "measured", "2024-04-24",
     "https://huggingface.co/Snowflake/snowflake-arctic-instruct"),

    # NVIDIA Nemotron 70B
    ("llama_3_1_nemotron_70b", "mmlu_pro", 70.0, "official", "measured", "2024-10-15",
     "https://huggingface.co/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"),
    ("llama_3_1_nemotron_70b", "ifeval", 90.0, "official", "measured", "2024-10-15",
     "https://huggingface.co/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"),
    ("llama_3_1_nemotron_70b", "mt_bench", 89.8, "official", "measured", "2024-10-15",
     "https://huggingface.co/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"),

    # Reka Flash 3
    ("reka_flash_3", "mmlu_pro", 65.0, "official", "measured", "2025-03-13",
     "https://huggingface.co/RekaAI/reka-flash-3"),
    ("reka_flash_3", "gpqa", 51.3, "official", "measured", "2025-03-13",
     "https://huggingface.co/RekaAI/reka-flash-3"),
    ("reka_flash_3", "aime", 39.0, "official", "measured", "2025-03-13",
     "https://huggingface.co/RekaAI/reka-flash-3"),

    # QwQ-32B
    ("qwq_32b", "aime", 79.5, "official", "measured", "2025-03-06",
     "https://huggingface.co/Qwen/QwQ-32B"),
    ("qwq_32b", "math", 90.6, "official", "measured", "2025-03-06",
     "https://huggingface.co/Qwen/QwQ-32B"),
    ("qwq_32b", "gpqa", 65.2, "official", "measured", "2025-03-06",
     "https://huggingface.co/Qwen/QwQ-32B"),
    ("qwq_32b", "livecodebench", 63.4, "official", "measured", "2025-03-06",
     "https://huggingface.co/Qwen/QwQ-32B"),

    # R1-Distill 시리즈
    ("r1_distill_llama_70b", "aime", 70.0, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B"),
    ("r1_distill_llama_70b", "math", 94.5, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B"),
    ("r1_distill_llama_70b", "gpqa", 65.2, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B"),
    ("r1_distill_llama_70b", "livecodebench", 57.5, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-70B"),
    ("r1_distill_qwen_32b", "aime", 72.6, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"),
    ("r1_distill_qwen_32b", "math", 94.3, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"),
    ("r1_distill_qwen_32b", "gpqa", 62.1, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"),
    ("r1_distill_qwen_32b", "livecodebench", 57.2, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B"),
    ("r1_distill_qwen_14b", "aime", 69.7, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"),
    ("r1_distill_qwen_14b", "math", 93.9, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"),
    ("r1_distill_qwen_14b", "gpqa", 59.1, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"),
    ("r1_distill_qwen_14b", "livecodebench", 53.1, "official", "measured", "2025-01-20",
     "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"),

    # Kakao Kanana
    ("kanana_2_30b_a3b", "kmmlu", 64.5, "official", "measured", "2026-01-15",
     "https://huggingface.co/kakaocorp/kanana-2-30b-a3b-instruct"),
    ("kanana_2_30b_a3b", "ifeval", 78.0, "official", "measured", "2026-01-15",
     "https://huggingface.co/kakaocorp/kanana-2-30b-a3b-instruct"),
    ("kanana_1_5_8b", "kmmlu", 50.5, "official", "measured", "2025-05-01",
     "https://huggingface.co/kakaocorp/kanana-1.5-8b-instruct-2505"),
    ("kanana_nano_2_1b", "kmmlu", 38.0, "official", "measured", "2025-02-01",
     "https://huggingface.co/kakaocorp/kanana-nano-2.1b-instruct"),
    ("kanana_nano_2_1b", "hae_rae", 65.3, "official", "measured", "2025-02-01",
     "https://huggingface.co/kakaocorp/kanana-nano-2.1b-instruct"),

    # Trillion Labs
    ("tri_21b", "kmmlu", 55.0, "official", "measured", "2025-09-01",
     "https://huggingface.co/trillionlabs/Tri-21B"),
    ("tri_21b", "hae_rae", 80.0, "official", "measured", "2025-09-01",
     "https://huggingface.co/trillionlabs/Tri-21B"),
    ("trillion_7b", "kmmlu", 47.0, "official", "measured", "2025-04-01",
     "https://huggingface.co/trillionlabs/Trillion-7B-preview"),
    ("trillion_7b", "hae_rae", 73.5, "official", "measured", "2025-04-01",
     "https://huggingface.co/trillionlabs/Trillion-7B-preview"),

    # Phi-3.5-MoE
    ("phi_3_5_moe", "mmlu_pro", 54.3, "official", "measured", "2024-08-20",
     "https://huggingface.co/microsoft/Phi-3.5-MoE-instruct"),
    ("phi_3_5_moe", "math", 54.3, "official", "measured", "2024-08-20",
     "https://huggingface.co/microsoft/Phi-3.5-MoE-instruct"),
    ("phi_3_5_moe", "humaneval", 70.7, "official", "measured", "2024-08-20",
     "https://huggingface.co/microsoft/Phi-3.5-MoE-instruct"),
]


# family/id → 회사명 매핑 (시드 dict에 company 필드 자동 주입)
# id 접두사 → 시리즈명 매핑. 가장 긴 매칭 우선.
_ID_PREFIX_TO_SERIES = [
    # Qwen
    ("qwen3_omni", "Qwen3-Omni"),
    ("qwen3_coder", "Qwen3-Coder"),
    ("qwen3_vl", "Qwen3-VL"),
    ("qwen2_5_vl", "Qwen2.5-VL"),
    ("qwen3", "Qwen3"),
    ("qwq", "QwQ"),
    # Llama
    ("llama_4", "Llama 4"),
    ("llama_3_3", "Llama 3.3"),
    ("llama_3_2", "Llama 3.2"),
    ("llama_3_1_nemotron", "Llama 3.1 Nemotron"),
    # DeepSeek
    ("deepseek_v3_2", "DeepSeek V3.2"),
    ("deepseek_v3_1", "DeepSeek V3.1"),
    ("r1_distill", "DeepSeek R1 Distill"),
    # GPT-OSS
    ("gpt_oss", "GPT-OSS"),
    # EXAONE
    ("exaone_4", "EXAONE 4.0"),
    ("exaone_deep", "EXAONE Deep"),
    ("exaone_3_5", "EXAONE 3.5"),
    # Korean
    ("ax_4", "A.X 4.0"),
    ("hyperclovax_seed", "HyperCLOVA X SEED"),
    ("kanana", "Kakao Kanana"),
    ("tri_", "Trillion Labs Tri"),
    ("trillion", "Trillion Labs Trillion"),
    ("kullm", "KULLM"),
    ("solar_pro", "Solar Pro"),
    # Mistral
    ("magistral", "Magistral"),
    ("devstral", "Devstral"),
    ("pixtral", "Pixtral"),
    ("mistral_small", "Mistral Small"),
    ("mixtral", "Mixtral"),
    # Gemma
    ("gemma_3", "Gemma 3"),
    # Phi
    ("phi_4_mini", "Phi-4 mini"),
    ("phi_4_multimodal", "Phi-4 Multimodal"),
    ("phi_4", "Phi-4"),
    ("phi_3_5_moe", "Phi-3.5-MoE"),
    # Hunyuan
    ("hunyuan", "Hunyuan"),
    # Yi
    ("yi_coder", "Yi-Coder"),
    ("yi_1_5", "Yi-1.5"),
    # InternLM
    ("internvl3", "InternVL3"),
    ("internlm3", "InternLM3"),
    # MiniCPM
    ("minicpm_v", "MiniCPM-V"),
    ("minicpm_4", "MiniCPM 4"),
    # SmolLM
    ("smollm3", "SmolLM3"),
    ("smollm2", "SmolLM2"),
    # Falcon
    ("falcon3", "Falcon 3"),
    # OLMo
    ("olmo2", "OLMo 2"),
    # Cohere
    ("aya_vision", "Aya Vision"),
    ("aya_expanse", "Aya Expanse"),
    ("command_a", "Command A"),
    # AI21
    ("jamba_1_5", "Jamba 1.5"),
    # Snowflake
    ("arctic", "Snowflake Arctic"),
    # Reka
    ("reka_flash", "Reka Flash"),
    # GLM
    ("glm_4_5", "GLM-4.5"),
    # MiniMax
    ("minimax_m1", "MiniMax M1"),
    # Moonshot
    ("kimi_k2", "Kimi K2"),
    # IBM Granite
    ("granite_4", "Granite 4"),
]


def _series_for(model: dict) -> str:
    mid = model["id"]
    for prefix, series in _ID_PREFIX_TO_SERIES:
        if mid.startswith(prefix):
            return series
    return model["family"].title()


_FAMILY_TO_COMPANY = {
    "llama": "Meta", "qwen": "Alibaba", "deepseek": "DeepSeek",
    "gpt-oss": "OpenAI", "exaone": "LG AI Research",
    "skt": "SK Telecom", "naver": "Naver",
    "solar": "Upstage", "kullm": "Korea Univ NLP Lab",
    "gemma": "Google", "mistral": "Mistral AI",
    "phi": "Microsoft", "ibm": "IBM", "glm": "Zhipu AI",
    "minimax": "MiniMax", "moonshot": "Moonshot AI",
    # 신규
    "hunyuan": "Tencent", "yi": "01.AI",
    "internlm": "Shanghai AI Lab", "openbmb": "OpenBMB (Tsinghua)",
    "smollm": "Hugging Face", "falcon": "TII (UAE)",
    "olmo": "AI2 (Allen Institute)", "cohere": "Cohere",
    "ai21": "AI21 Labs", "snowflake": "Snowflake",
    "nvidia": "NVIDIA", "reka": "Reka AI",
    "kakao": "Kakao", "trillion": "Trillion Labs",
}

# id 단위 override (family로 구분 안 되는 경우)
_ID_TO_COMPANY = {}


def _company_for(model: dict) -> str:
    if model["id"] in _ID_TO_COMPANY:
        return _ID_TO_COMPANY[model["id"]]
    return _FAMILY_TO_COMPANY.get(model["family"], model["family"].title())


def main() -> None:
    SEED_DIR.mkdir(parents=True, exist_ok=True)

    enriched = [
        {**m, "company": _company_for(m), "series": _series_for(m)}
        for m in MODELS
    ]
    df_models = pd.DataFrame(enriched)
    df_models.to_parquet(SEED_DIR / "models.parquet", index=False)

    df_bench = pd.DataFrame(BENCHMARKS, columns=[
        "model_id", "benchmark_id", "score", "measured_by",
        "confidence", "measured_at", "source_url",
    ])
    df_bench["max_score"] = 100.0
    df_bench["normalized_0_100"] = df_bench["score"]
    df_bench.loc[df_bench["benchmark_id"] == "logickor", "max_score"] = 10.0
    df_bench.loc[df_bench["benchmark_id"] == "logickor", "normalized_0_100"] = (
        df_bench.loc[df_bench["benchmark_id"] == "logickor", "score"] * 10
    )
    df_bench.to_parquet(SEED_DIR / "benchmarks.parquet", index=False)

    print(f"Wrote {len(df_models)} models to {SEED_DIR/'models.parquet'}")
    print(f"Wrote {len(df_bench)} benchmark rows to {SEED_DIR/'benchmarks.parquet'}")


if __name__ == "__main__":
    main()
